// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 12.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Catrobat.IDE.WindowsPhone.TestsUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertNavigateToNewProgramm - Verwenden Sie "AssertNavigateToNewProgrammExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToNewProgramm()
        {
            #region Variable Declarations
            XamlText uINEWPROGRAMText = this.UIPocketCodeIDEWindow.UINEWPROGRAMText;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'DisplayText' von "NEW PROGRAM" Bezeichnung ist gleich 'NEW PROGRAM'
            Assert.AreEqual(this.AssertNavigateToNewProgrammExpectedValues.UINEWPROGRAMTextDisplayText, uINEWPROGRAMText.DisplayText, "Navigated to wrong page.");
        }
        
        /// <summary>
        /// AssertNavigateToOnlineProjectHub - Verwenden Sie "AssertNavigateToOnlineProjectHubExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToOnlineProjectHub()
        {
            #region Variable Declarations
            XamlHubSection uIHubSectionOnlineProjHubSection = this.UIPocketCodeIDEWindow.UIMainHubHub.UIHubSectionOnlineProjHubSection;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionOnlineProjects" Hubabschnitt ist gleich 'HubSectionOnlineProjects'
            Assert.AreEqual(this.AssertNavigateToOnlineProjectHubExpectedValues.UIHubSectionOnlineProjHubSectionAutomationId, uIHubSectionOnlineProjHubSection.AutomationId, "Navigated to the wrong HubSection");
        }
        
        /// <summary>
        /// AssertNavigateToLocalProjectHub - Verwenden Sie "AssertNavigateToLocalProjectHubExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToLocalProjectHub()
        {
            #region Variable Declarations
            XamlHubSection uIHubSectionLocalProjeHubSection = this.UIPocketCodeIDEWindow.UIMainHubHub.UIHubSectionLocalProjeHubSection;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionLocalProjects" Hubabschnitt ist gleich 'HubSectionLocalProjects'
            Assert.AreEqual(this.AssertNavigateToLocalProjectHubExpectedValues.UIHubSectionLocalProjeHubSectionAutomationId, uIHubSectionLocalProjeHubSection.AutomationId, "Navigated to wrong HubSection");
        }
        
        #region Properties
        public virtual AssertNavigateToNewProgrammExpectedValues AssertNavigateToNewProgrammExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToNewProgrammExpectedValues == null))
                {
                    this.mAssertNavigateToNewProgrammExpectedValues = new AssertNavigateToNewProgrammExpectedValues();
                }
                return this.mAssertNavigateToNewProgrammExpectedValues;
            }
        }
        
        public virtual AssertNavigateToOnlineProjectHubExpectedValues AssertNavigateToOnlineProjectHubExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToOnlineProjectHubExpectedValues == null))
                {
                    this.mAssertNavigateToOnlineProjectHubExpectedValues = new AssertNavigateToOnlineProjectHubExpectedValues();
                }
                return this.mAssertNavigateToOnlineProjectHubExpectedValues;
            }
        }
        
        public virtual AssertNavigateToLocalProjectHubExpectedValues AssertNavigateToLocalProjectHubExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToLocalProjectHubExpectedValues == null))
                {
                    this.mAssertNavigateToLocalProjectHubExpectedValues = new AssertNavigateToLocalProjectHubExpectedValues();
                }
                return this.mAssertNavigateToLocalProjectHubExpectedValues;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIPocketCodeIDEWindow UIPocketCodeIDEWindow
        {
            get
            {
                if ((this.mUIPocketCodeIDEWindow == null))
                {
                    this.mUIPocketCodeIDEWindow = new UIPocketCodeIDEWindow();
                }
                return this.mUIPocketCodeIDEWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertNavigateToNewProgrammExpectedValues mAssertNavigateToNewProgrammExpectedValues;
        
        private AssertNavigateToOnlineProjectHubExpectedValues mAssertNavigateToOnlineProjectHubExpectedValues;
        
        private AssertNavigateToLocalProjectHubExpectedValues mAssertNavigateToLocalProjectHubExpectedValues;
        
        private UIItemWindow mUIItemWindow;
        
        private UIPocketCodeIDEWindow mUIPocketCodeIDEWindow;
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToNewProgramm" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToNewProgrammExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'DisplayText' von "NEW PROGRAM" Bezeichnung ist gleich 'NEW PROGRAM'
        /// </summary>
        public string UINEWPROGRAMTextDisplayText = "NEW PROGRAM";
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToOnlineProjectHub" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToOnlineProjectHubExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionOnlineProjects" Hubabschnitt ist gleich 'HubSectionOnlineProjects'
        /// </summary>
        public string UIHubSectionOnlineProjHubSectionAutomationId = "HubSectionOnlineProjects";
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToLocalProjectHub" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToLocalProjectHubExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionLocalProjects" Hubabschnitt ist gleich 'HubSectionLocalProjects'
        /// </summary>
        public string UIHubSectionLocalProjeHubSectionAutomationId = "HubSectionLocalProjects";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIItemWindow : UITestControl
    {
        
        public UIItemWindow()
        {
            #region Suchkriterien
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UITestControl UINewButton
        {
            get
            {
                if ((this.mUINewButton == null))
                {
                    this.mUINewButton = new UITestControl(this);
                    #region Suchkriterien
                    this.mUINewButton.TechnologyName = "UIA";
                    this.mUINewButton.SearchProperties["FrameworkId"] = "UIX";
                    this.mUINewButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mUINewButton.SearchProperties[UITestControl.PropertyNames.Name] = "new";
                    #endregion
                }
                return this.mUINewButton;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUINewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIPocketCodeIDEWindow : XamlWindow
    {
        
        public UIPocketCodeIDEWindow()
        {
            #region Suchkriterien
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Pocket Code IDE";
            #endregion
        }
        
        #region Properties
        public XamlText UINEWPROGRAMText
        {
            get
            {
                if ((this.mUINEWPROGRAMText == null))
                {
                    this.mUINEWPROGRAMText = new XamlText(this);
                    #region Suchkriterien
                    this.mUINEWPROGRAMText.SearchProperties[XamlText.PropertyNames.Name] = "NEW PROGRAM";
                    #endregion
                }
                return this.mUINEWPROGRAMText;
            }
        }
        
        public UIMainHubHub UIMainHubHub
        {
            get
            {
                if ((this.mUIMainHubHub == null))
                {
                    this.mUIMainHubHub = new UIMainHubHub(this);
                }
                return this.mUIMainHubHub;
            }
        }
        #endregion
        
        #region Fields
        private XamlText mUINEWPROGRAMText;
        
        private UIMainHubHub mUIMainHubHub;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIMainHubHub : XamlHub
    {
        
        public UIMainHubHub(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[XamlHub.PropertyNames.AutomationId] = "MainHub";
            #endregion
        }
        
        #region Properties
        public XamlHubSection UIHubSectionOnlineProjHubSection
        {
            get
            {
                if ((this.mUIHubSectionOnlineProjHubSection == null))
                {
                    this.mUIHubSectionOnlineProjHubSection = new XamlHubSection(this);
                    #region Suchkriterien
                    this.mUIHubSectionOnlineProjHubSection.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "HubSectionOnlineProjects";
                    #endregion
                }
                return this.mUIHubSectionOnlineProjHubSection;
            }
        }
        
        public XamlHubSection UIHubSectionLocalProjeHubSection
        {
            get
            {
                if ((this.mUIHubSectionLocalProjeHubSection == null))
                {
                    this.mUIHubSectionLocalProjeHubSection = new XamlHubSection(this);
                    #region Suchkriterien
                    this.mUIHubSectionLocalProjeHubSection.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "HubSectionLocalProjects";
                    #endregion
                }
                return this.mUIHubSectionLocalProjeHubSection;
            }
        }
        #endregion
        
        #region Fields
        private XamlHubSection mUIHubSectionOnlineProjHubSection;
        
        private XamlHubSection mUIHubSectionLocalProjeHubSection;
        #endregion
    }
}
