// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 12.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Catrobat.IDE.WindowsPhone.TestsUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertNavigateToLocalProgramsHubSection - Verwenden Sie "AssertNavigateToLocalProgramsHubSectionExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToLocalProgramsHubSection()
        {
            #region Variable Declarations
            XamlHubSection uIHubSectionLocalProgrHubSection = this.UIPocketCodeIDEWindow.UIMainHubHub.UIHubSectionLocalProgrHubSection;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionLocalPrograms" Hubabschnitt ist gleich 'HubSectionLocalPrograms'
            Assert.AreEqual(this.AssertNavigateToLocalProgramsHubSectionExpectedValues.UIHubSectionLocalProgrHubSectionAutomationId, uIHubSectionLocalProgrHubSection.AutomationId, "Navigated to the wrong hubsection");
        }
        
        /// <summary>
        /// AssertNavigateToNewProgramm - Verwenden Sie "AssertNavigateToNewProgrammExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToNewProgramm()
        {
            #region Variable Declarations
            XamlText uINEWPROGRAMText = this.UIPocketCodeIDEWindow.UINEWPROGRAMText;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'DisplayText' von "NEW PROGRAM" Bezeichnung ist gleich 'NEW PROGRAM'
            Assert.AreEqual(this.AssertNavigateToNewProgrammExpectedValues.UINEWPROGRAMTextDisplayText, uINEWPROGRAMText.DisplayText, "Navigated to wrong page.");
        }
        
        /// <summary>
        /// AssertNavigateToOnlineProgramsHubSection - Verwenden Sie "AssertNavigateToOnlineProgramsHubSectionExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertNavigateToOnlineProgramsHubSection()
        {
            #region Variable Declarations
            XamlHubSection uIHubSectionOnlineProgHubSection = this.UIPocketCodeIDEWindow.UIMainHubHub.UIHubSectionOnlineProgHubSection;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionOnlinePrograms" Hubabschnitt ist gleich 'HubSectionOnlinePrograms'
            Assert.AreEqual(this.AssertNavigateToOnlineProgramsHubSectionExpectedValues.UIHubSectionOnlineProgHubSectionAutomationId, uIHubSectionOnlineProgHubSection.AutomationId, "Navigated to the wrong hubsection");
        }
        
        #region Properties
        public virtual AssertNavigateToLocalProgramsHubSectionExpectedValues AssertNavigateToLocalProgramsHubSectionExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToLocalProgramsHubSectionExpectedValues == null))
                {
                    this.mAssertNavigateToLocalProgramsHubSectionExpectedValues = new AssertNavigateToLocalProgramsHubSectionExpectedValues();
                }
                return this.mAssertNavigateToLocalProgramsHubSectionExpectedValues;
            }
        }
        
        public virtual AssertNavigateToNewProgrammExpectedValues AssertNavigateToNewProgrammExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToNewProgrammExpectedValues == null))
                {
                    this.mAssertNavigateToNewProgrammExpectedValues = new AssertNavigateToNewProgrammExpectedValues();
                }
                return this.mAssertNavigateToNewProgrammExpectedValues;
            }
        }
        
        public virtual AssertNavigateToOnlineProgramsHubSectionExpectedValues AssertNavigateToOnlineProgramsHubSectionExpectedValues
        {
            get
            {
                if ((this.mAssertNavigateToOnlineProgramsHubSectionExpectedValues == null))
                {
                    this.mAssertNavigateToOnlineProgramsHubSectionExpectedValues = new AssertNavigateToOnlineProgramsHubSectionExpectedValues();
                }
                return this.mAssertNavigateToOnlineProgramsHubSectionExpectedValues;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIPocketCodeIDEWindow UIPocketCodeIDEWindow
        {
            get
            {
                if ((this.mUIPocketCodeIDEWindow == null))
                {
                    this.mUIPocketCodeIDEWindow = new UIPocketCodeIDEWindow();
                }
                return this.mUIPocketCodeIDEWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertNavigateToLocalProgramsHubSectionExpectedValues mAssertNavigateToLocalProgramsHubSectionExpectedValues;
        
        private AssertNavigateToNewProgrammExpectedValues mAssertNavigateToNewProgrammExpectedValues;
        
        private AssertNavigateToOnlineProgramsHubSectionExpectedValues mAssertNavigateToOnlineProgramsHubSectionExpectedValues;
        
        private UIItemWindow mUIItemWindow;
        
        private UIPocketCodeIDEWindow mUIPocketCodeIDEWindow;
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToLocalProgramsHubSection" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToLocalProgramsHubSectionExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionLocalPrograms" Hubabschnitt ist gleich 'HubSectionLocalPrograms'
        /// </summary>
        public string UIHubSectionLocalProgrHubSectionAutomationId = "HubSectionLocalPrograms";
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToNewProgramm" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToNewProgrammExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'DisplayText' von "NEW PROGRAM" Bezeichnung ist gleich 'NEW PROGRAM'
        /// </summary>
        public string UINEWPROGRAMTextDisplayText = "NEW PROGRAM";
        #endregion
    }
    
    /// <summary>
    /// An "AssertNavigateToOnlineProgramsHubSection" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class AssertNavigateToOnlineProgramsHubSectionExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'AutomationId' von "HubSectionOnlinePrograms" Hubabschnitt ist gleich 'HubSectionOnlinePrograms'
        /// </summary>
        public string UIHubSectionOnlineProgHubSectionAutomationId = "HubSectionOnlinePrograms";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIItemWindow : UITestControl
    {
        
        public UIItemWindow()
        {
            #region Suchkriterien
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UITestControl UINewButton
        {
            get
            {
                if ((this.mUINewButton == null))
                {
                    this.mUINewButton = new UITestControl(this);
                    #region Suchkriterien
                    this.mUINewButton.TechnologyName = "UIA";
                    this.mUINewButton.SearchProperties["FrameworkId"] = "UIX";
                    this.mUINewButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mUINewButton.SearchProperties[UITestControl.PropertyNames.Name] = "new";
                    #endregion
                }
                return this.mUINewButton;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUINewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIPocketCodeIDEWindow : XamlWindow
    {
        
        public UIPocketCodeIDEWindow()
        {
            #region Suchkriterien
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Pocket Code IDE";
            #endregion
        }
        
        #region Properties
        public XamlText UINEWPROGRAMText
        {
            get
            {
                if ((this.mUINEWPROGRAMText == null))
                {
                    this.mUINEWPROGRAMText = new XamlText(this);
                    #region Suchkriterien
                    this.mUINEWPROGRAMText.SearchProperties[XamlText.PropertyNames.Name] = "NEW PROGRAM";
                    #endregion
                }
                return this.mUINEWPROGRAMText;
            }
        }
        
        public UIMainHubHub UIMainHubHub
        {
            get
            {
                if ((this.mUIMainHubHub == null))
                {
                    this.mUIMainHubHub = new UIMainHubHub(this);
                }
                return this.mUIMainHubHub;
            }
        }
        #endregion
        
        #region Fields
        private XamlText mUINEWPROGRAMText;
        
        private UIMainHubHub mUIMainHubHub;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.30501.0")]
    public class UIMainHubHub : XamlHub
    {
        
        public UIMainHubHub(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[XamlHub.PropertyNames.AutomationId] = "MainHub";
            #endregion
        }
        
        #region Properties
        public XamlHubSection UIHubSectionOnlineProgHubSection
        {
            get
            {
                if ((this.mUIHubSectionOnlineProgHubSection == null))
                {
                    this.mUIHubSectionOnlineProgHubSection = new XamlHubSection(this);
                    #region Suchkriterien
                    this.mUIHubSectionOnlineProgHubSection.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "HubSectionOnlinePrograms";
                    #endregion
                }
                return this.mUIHubSectionOnlineProgHubSection;
            }
        }
        
        public XamlHubSection UIHubSectionLocalProgrHubSection
        {
            get
            {
                if ((this.mUIHubSectionLocalProgrHubSection == null))
                {
                    this.mUIHubSectionLocalProgrHubSection = new XamlHubSection(this);
                    #region Suchkriterien
                    this.mUIHubSectionLocalProgrHubSection.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "HubSectionLocalPrograms";
                    #endregion
                }
                return this.mUIHubSectionLocalProgrHubSection;
            }
        }
        #endregion
        
        #region Fields
        private XamlHubSection mUIHubSectionOnlineProgHubSection;
        
        private XamlHubSection mUIHubSectionLocalProgrHubSection;
        #endregion
    }
}
