//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDECommon.Resources.IDE.Editor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDECommon.Resources.IDE.Editor.EditorResources", typeof(EditorResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string ActionPlural {
            get {
                return ResourceManager.GetString("ActionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string ActionSingular {
            get {
                return ResourceManager.GetString("ActionSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast message.
        /// </summary>
        public static string BroadcastMessage {
            get {
                return ResourceManager.GetString("BroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new costume.
        /// </summary>
        public static string ButtonAddCostume {
            get {
                return ResourceManager.GetString("ButtonAddCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new object.
        /// </summary>
        public static string ButtonAddObject {
            get {
                return ResourceManager.GetString("ButtonAddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string ButtonAddScript {
            get {
                return ResourceManager.GetString("ButtonAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sound.
        /// </summary>
        public static string ButtonAddSound {
            get {
                return ResourceManager.GetString("ButtonAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string ButtonChange {
            get {
                return ResourceManager.GetString("ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play project.
        /// </summary>
        public static string ButtonPlayProject {
            get {
                return ResourceManager.GetString("ButtonPlayProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string ButtonUse {
            get {
                return ResourceManager.GetString("ButtonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selektierung aufheben.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume name.
        /// </summary>
        public static string CostumeName {
            get {
                return ResourceManager.GetString("CostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costumes.
        /// </summary>
        public static string CostumePlural {
            get {
                return ResourceManager.GetString("CostumePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costume.
        /// </summary>
        public static string CostumeSingular {
            get {
                return ResourceManager.GetString("CostumeSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery.
        /// </summary>
        public static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full size.
        /// </summary>
        public static string ImageSizeFullSize {
            get {
                return ResourceManager.GetString("ImageSizeFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string ImageSizeLarge {
            get {
                return ResourceManager.GetString("ImageSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string ImageSizeMedium {
            get {
                return ResourceManager.GetString("ImageSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small.
        /// </summary>
        public static string ImageSizeSmall {
            get {
                return ResourceManager.GetString("ImageSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Library.
        /// </summary>
        public static string MediaLibrary {
            get {
                return ResourceManager.GetString("MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string MenuProjectSettings {
            get {
                return ResourceManager.GetString("MenuProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start site.
        /// </summary>
        public static string MenuStartSite {
            get {
                return ResourceManager.GetString("MenuStartSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string MessageBoxDeleteHeader {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected {1}..
        /// </summary>
        public static string MessageBoxDeleteText {
            get {
                return ResourceManager.GetString("MessageBoxDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string MessageBoxNotEnoughSpaceImageHeader {
            get {
                return ResourceManager.GetString("MessageBoxNotEnoughSpaceImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the image cannot be saved..
        /// </summary>
        public static string MessageBoxNotEnoughSpaceImageText {
            get {
                return ResourceManager.GetString("MessageBoxNotEnoughSpaceImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string MessageBoxNotEnoughSpaceSoundHeader {
            get {
                return ResourceManager.GetString("MessageBoxNotEnoughSpaceSoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the sound cannot be saved..
        /// </summary>
        public static string MessageBoxNotEnoughSpaceSoundText {
            get {
                return ResourceManager.GetString("MessageBoxNotEnoughSpaceSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported format.
        /// </summary>
        public static string MessageBoxWrongImageFormatHeader {
            get {
                return ResourceManager.GetString("MessageBoxWrongImageFormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the image has a not supported format..
        /// </summary>
        public static string MessageBoxWrongImageFormatText {
            get {
                return ResourceManager.GetString("MessageBoxWrongImageFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string NewAction {
            get {
                return ResourceManager.GetString("NewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new costume.
        /// </summary>
        public static string NewCostume {
            get {
                return ResourceManager.GetString("NewCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new object.
        /// </summary>
        public static string NewObject {
            get {
                return ResourceManager.GetString("NewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sound.
        /// </summary>
        public static string NewSound {
            get {
                return ResourceManager.GetString("NewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No costume selected.
        /// </summary>
        public static string NoCostumeSelected {
            get {
                return ResourceManager.GetString("NoCostumeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message selected.
        /// </summary>
        public static string NoMessageSelected {
            get {
                return ResourceManager.GetString("NoMessageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound selected.
        /// </summary>
        public static string NoSoundSelected {
            get {
                return ResourceManager.GetString("NoSoundSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object selected.
        /// </summary>
        public static string NoSpriteSelected {
            get {
                return ResourceManager.GetString("NoSpriteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing....
        /// </summary>
        public static string NothingItem {
            get {
                return ResourceManager.GetString("NothingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        public static string ObjectPlural {
            get {
                return ResourceManager.GetString("ObjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        public static string ObjectSingular {
            get {
                return ResourceManager.GetString("ObjectSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string PivotActions {
            get {
                return ResourceManager.GetString("PivotActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costumes.
        /// </summary>
        public static string PivotCostumes {
            get {
                return ResourceManager.GetString("PivotCostumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string PivotObjects {
            get {
                return ResourceManager.GetString("PivotObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string PivotSounds {
            get {
                return ResourceManager.GetString("PivotSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        public static string Recorder {
            get {
                return ResourceManager.GetString("Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec.
        /// </summary>
        public static string RecorderRecord {
            get {
                return ResourceManager.GetString("RecorderRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string RecorderRecordTime {
            get {
                return ResourceManager.GetString("RecorderRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start recording.
        /// </summary>
        public static string RecorderStart {
            get {
                return ResourceManager.GetString("RecorderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string RecorderStop {
            get {
                return ResourceManager.GetString("RecorderStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving image.
        /// </summary>
        public static string SavingImage {
            get {
                return ResourceManager.GetString("SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound name.
        /// </summary>
        public static string SoundName {
            get {
                return ResourceManager.GetString("SoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sounds.
        /// </summary>
        public static string SoundPlural {
            get {
                return ResourceManager.GetString("SoundPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        public static string SoundSingular {
            get {
                return ResourceManager.GetString("SoundSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        public static string SpriteName {
            get {
                return ResourceManager.GetString("SpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE COSTUME NAME.
        /// </summary>
        public static string TitleChangeCostumeName {
            get {
                return ResourceManager.GetString("TitleChangeCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE SOUND NAME.
        /// </summary>
        public static string TitleChangeSoundName {
            get {
                return ResourceManager.GetString("TitleChangeSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE OBJECT NAME.
        /// </summary>
        public static string TitleChangeSpriteName {
            get {
                return ResourceManager.GetString("TitleChangeSpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE BRICK.
        /// </summary>
        public static string TitleChooseBrick {
            get {
                return ResourceManager.GetString("TitleChooseBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE CATEGORY.
        /// </summary>
        public static string TitleChooseCategory {
            get {
                return ResourceManager.GetString("TitleChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE COSTUME NAME.
        /// </summary>
        public static string TitleChooseCostumeName {
            get {
                return ResourceManager.GetString("TitleChooseCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND.
        /// </summary>
        public static string TitleChooseSound {
            get {
                return ResourceManager.GetString("TitleChooseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND NAME.
        /// </summary>
        public static string TitleChooseSoundName {
            get {
                return ResourceManager.GetString("TitleChooseSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string TitleNewAction {
            get {
                return ResourceManager.GetString("TitleNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW BROADCAST MESSAGE.
        /// </summary>
        public static string TitleNewBroadcastMessage {
            get {
                return ResourceManager.GetString("TitleNewBroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW COSTUME.
        /// </summary>
        public static string TitleNewCostume {
            get {
                return ResourceManager.GetString("TitleNewCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SOUND.
        /// </summary>
        public static string TitleNewSound {
            get {
                return ResourceManager.GetString("TitleNewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW OBJECT.
        /// </summary>
        public static string TitleNewSprite {
            get {
                return ResourceManager.GetString("TitleNewSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT SETTINGS.
        /// </summary>
        public static string TitleProjectSettings {
            get {
                return ResourceManager.GetString("TitleProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD SOUND.
        /// </summary>
        public static string TitleRecorder {
            get {
                return ResourceManager.GetString("TitleRecorder", resourceCulture);
            }
        }
    }
}
