//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDECommon.Resources.IDE.Formula {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormulaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormulaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDECommon.Resources.IDE.Formula.FormulaResources", typeof(FormulaResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationX.
        /// </summary>
        public static string ACCELERATION_X {
            get {
                return ResourceManager.GetString("ACCELERATION_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationY.
        /// </summary>
        public static string ACCELERATION_Y {
            get {
                return ResourceManager.GetString("ACCELERATION_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationZ.
        /// </summary>
        public static string ACCELERATION_Z {
            get {
                return ResourceManager.GetString("ACCELERATION_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brightness.
        /// </summary>
        public static string BRIGHTNESS {
            get {
                return ResourceManager.GetString("BRIGHTNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string ClosedBrecket {
            get {
                return ResourceManager.GetString("ClosedBrecket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compassdirec.
        /// </summary>
        public static string COMPASSDIRECTION {
            get {
                return ResourceManager.GetString("COMPASSDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DecimalPointCharacter {
            get {
                return ResourceManager.GetString("DecimalPointCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        public static string DIRECTION {
            get {
                return ResourceManager.GetString("DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclinationX.
        /// </summary>
        public static string INCLINATION_X {
            get {
                return ResourceManager.GetString("INCLINATION_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclinationY.
        /// </summary>
        public static string INCLINATION_Y {
            get {
                return ResourceManager.GetString("INCLINATION_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        public static string LAYER {
            get {
                return ResourceManager.GetString("LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string LogicEqual {
            get {
                return ResourceManager.GetString("LogicEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string LogicOr {
            get {
                return ResourceManager.GetString("LogicOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectX.
        /// </summary>
        public static string OBJECT_X {
            get {
                return ResourceManager.GetString("OBJECT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectY.
        /// </summary>
        public static string OBJECT_Y {
            get {
                return ResourceManager.GetString("OBJECT_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string OpenBrecket {
            get {
                return ResourceManager.GetString("OpenBrecket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string ParameterSeperator {
            get {
                return ResourceManager.GetString("ParameterSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparency.
        /// </summary>
        public static string TRANSPARENCY {
            get {
                return ResourceManager.GetString("TRANSPARENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
