namespace Catrobat.IDE.Core.ViewModels
{
    public enum ViewModelMessagingToken
    {
        LoadSettings,
        SaveSettings,
        LookListener,
        SoundNameListener,
        CurrentSpriteChangedListener,
        SpriteNameListener,
        BroadcastObjectListener,
        BroadcastMessageListener,
        ScriptBrickCollectionListener,
        SelectedBrickListener,
        CurrentProgramChangedListener,
        LocalProgramsChangedListener,
        SelectedOnlineProgramChangedListener,
        ContextListener,
        ThemeChooserListener,
        DownloadProgramStartedListener,
        UploadProgramStartedListener,
        SelectedUserVariableChangedListener,
        ShareProgramHeaderListener,
        CurrentProgramHeaderChangedListener,
        LookImageListener,
        LookImageToSaveListener,
        ScriptBrickCategoryListener,
        SoundStreamListener,
        PlayProgramNameListener,
        IsPlayerStartFromTileListener,
        FormulaEvaluated,
        ClearPageCache,
        ExportStreamChanged,
        ToastNotificationActivated
    }
}