namespace Catrobat.IDE.Core.ViewModels
{
    public enum ViewModelMessagingToken
    {
        LoadSettings,
        SaveSettings,
        LookListener,
        SoundNameListener,
        CurrentSpriteChangedListener,
        SpriteNameListener,
        //SpriteListListener,
        //ProjectNameListener,
        BroadcastObjectListener,
        BroadcastMessageListener,
        ScriptBrickCollectionListener,
        SelectedBrickListener,
        CurrentProjectChangedListener,
        LocalProjectsChangedListener,
        SelectedOnlineProjectChangedListener,
        ContextListener,
        ThemeChooserListener,
        PinProjectHeaderListener,
        DownloadProjectStartedListener,
        UploadProjectStartedListener,
        SelectedUserVariableChangedListener,
        ShareProjectHeaderListener,
        CurrentProjectHeaderChangedListener,
        LookImageListener,
        LookImageToSaveListener,
        ScriptBrickCategoryListener,
        SoundStreamListener,
        PlayProjectNameListener,
        IsPlayerStartFromTileListener,
        FormulaEvaluated
    }
}