//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDE.Core.Resources.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDE.Core.Resources.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string App_FlowDirection {
            get {
                return ResourceManager.GetString("App_FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string App_ResourceLanguage {
            get {
                return ResourceManager.GetString("App_ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast.
        /// </summary>
        public static string Brick_Broadcast {
            get {
                return ResourceManager.GetString("Brick_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast and wait.
        /// </summary>
        public static string Brick_BroadcastWait {
            get {
                return ResourceManager.GetString("Brick_BroadcastWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string Brick_ButtonNew {
            get {
                return ResourceManager.GetString("Brick_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Brick_CategoryControl {
            get {
                return ResourceManager.GetString("Brick_CategoryControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks.
        /// </summary>
        public static string Brick_CategoryLooks {
            get {
                return ResourceManager.GetString("Brick_CategoryLooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        public static string Brick_CategoryMotion {
            get {
                return ResourceManager.GetString("Brick_CategoryMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Brick_CategorySound {
            get {
                return ResourceManager.GetString("Brick_CategorySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Brick_CategoryVariables {
            get {
                return ResourceManager.GetString("Brick_CategoryVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change brightness by.
        /// </summary>
        public static string Brick_ChangeBrightnessBy {
            get {
                return ResourceManager.GetString("Brick_ChangeBrightnessBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change ghost effect by.
        /// </summary>
        public static string Brick_ChangeGhostEffectBy {
            get {
                return ResourceManager.GetString("Brick_ChangeGhostEffectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change size by.
        /// </summary>
        public static string Brick_ChangeSizeBy {
            get {
                return ResourceManager.GetString("Brick_ChangeSizeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change variable.
        /// </summary>
        public static string Brick_ChangeVariable {
            get {
                return ResourceManager.GetString("Brick_ChangeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Brick_ChangeVariableBy {
            get {
                return ResourceManager.GetString("Brick_ChangeVariableBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change volume by.
        /// </summary>
        public static string Brick_ChangeVolumeBy {
            get {
                return ResourceManager.GetString("Brick_ChangeVolumeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change X by.
        /// </summary>
        public static string Brick_ChangeXBy {
            get {
                return ResourceManager.GetString("Brick_ChangeXBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Y by.
        /// </summary>
        public static string Brick_ChangeYBy {
            get {
                return ResourceManager.GetString("Brick_ChangeYBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear graphic effects.
        /// </summary>
        public static string Brick_ClearGraphicEffects {
            get {
                return ResourceManager.GetString("Brick_ClearGraphicEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to come to front.
        /// </summary>
        public static string Brick_ComeToFront {
            get {
                return ResourceManager.GetString("Brick_ComeToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        public static string Brick_Degrees {
            get {
                return ResourceManager.GetString("Brick_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever.
        /// </summary>
        public static string Brick_Forever {
            get {
                return ResourceManager.GetString("Brick_Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of loop.
        /// </summary>
        public static string Brick_ForeverLoopEnd {
            get {
                return ResourceManager.GetString("Brick_ForeverLoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glide.
        /// </summary>
        public static string Brick_GlideToGlide {
            get {
                return ResourceManager.GetString("Brick_GlideToGlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Brick_GlideToTo {
            get {
                return ResourceManager.GetString("Brick_GlideToTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        public static string Brick_GoNStepsBackGo {
            get {
                return ResourceManager.GetString("Brick_GoNStepsBackGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layers.
        /// </summary>
        public static string Brick_GoNStepsBackStepsBack {
            get {
                return ResourceManager.GetString("Brick_GoNStepsBackStepsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string Brick_Hide {
            get {
                return ResourceManager.GetString("Brick_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        public static string Brick_IfLogicBegin {
            get {
                return ResourceManager.GetString("Brick_IfLogicBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true, then.
        /// </summary>
        public static string Brick_IfLogicBeginTrue {
            get {
                return ResourceManager.GetString("Brick_IfLogicBeginTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        public static string Brick_IfLogicElse {
            get {
                return ResourceManager.GetString("Brick_IfLogicElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end if.
        /// </summary>
        public static string Brick_IfLogicEnd {
            get {
                return ResourceManager.GetString("Brick_IfLogicEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if on edge, bounce.
        /// </summary>
        public static string Brick_IfOnEdgeBounce {
            get {
                return ResourceManager.GetString("Brick_IfOnEdgeBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string Brick_MoveNStepsMove {
            get {
                return ResourceManager.GetString("Brick_MoveNStepsMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps.
        /// </summary>
        public static string Brick_MoveNStepsSteps {
            get {
                return ResourceManager.GetString("Brick_MoveNStepsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next look.
        /// </summary>
        public static string Brick_NextCostume {
            get {
                return ResourceManager.GetString("Brick_NextCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string Brick_Note {
            get {
                return ResourceManager.GetString("Brick_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place at.
        /// </summary>
        public static string Brick_PlaceAt {
            get {
                return ResourceManager.GetString("Brick_PlaceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play sound.
        /// </summary>
        public static string Brick_PlaySound {
            get {
                return ResourceManager.GetString("Brick_PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point in direction.
        /// </summary>
        public static string Brick_PointInDirection {
            get {
                return ResourceManager.GetString("Brick_PointInDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point towards.
        /// </summary>
        public static string Brick_PointTo {
            get {
                return ResourceManager.GetString("Brick_PointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string Brick_Repeat {
            get {
                return ResourceManager.GetString("Brick_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of loop.
        /// </summary>
        public static string Brick_RepeatLoopEnd {
            get {
                return ResourceManager.GetString("Brick_RepeatLoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Brick_Seconds {
            get {
                return ResourceManager.GetString("Brick_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set brightness to.
        /// </summary>
        public static string Brick_SetBrightnessTo {
            get {
                return ResourceManager.GetString("Brick_SetBrightnessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set look.
        /// </summary>
        public static string Brick_SetCostume {
            get {
                return ResourceManager.GetString("Brick_SetCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set ghost effect to.
        /// </summary>
        public static string Brick_SetGhostEffectTo {
            get {
                return ResourceManager.GetString("Brick_SetGhostEffectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set size to.
        /// </summary>
        public static string Brick_SetSizeTo {
            get {
                return ResourceManager.GetString("Brick_SetSizeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set variable.
        /// </summary>
        public static string Brick_SetVariable {
            get {
                return ResourceManager.GetString("Brick_SetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Brick_SetVariableTo {
            get {
                return ResourceManager.GetString("Brick_SetVariableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set volume to.
        /// </summary>
        public static string Brick_SetVolumeTo {
            get {
                return ResourceManager.GetString("Brick_SetVolumeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set X to.
        /// </summary>
        public static string Brick_SetXTo {
            get {
                return ResourceManager.GetString("Brick_SetXTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Y to.
        /// </summary>
        public static string Brick_SetYTo {
            get {
                return ResourceManager.GetString("Brick_SetYTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string Brick_Show {
            get {
                return ResourceManager.GetString("Brick_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speak.
        /// </summary>
        public static string Brick_Speak {
            get {
                return ResourceManager.GetString("Brick_Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop all sounds.
        /// </summary>
        public static string Brick_StopAllSounds {
            get {
                return ResourceManager.GetString("Brick_StopAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string Brick_Times {
            get {
                return ResourceManager.GetString("Brick_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn left.
        /// </summary>
        public static string Brick_TurnLeft {
            get {
                return ResourceManager.GetString("Brick_TurnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn right.
        /// </summary>
        public static string Brick_TurnRight {
            get {
                return ResourceManager.GetString("Brick_TurnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait.
        /// </summary>
        public static string Brick_Wait {
            get {
                return ResourceManager.GetString("Brick_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when I receive.
        /// </summary>
        public static string Brick_WhenIReceive {
            get {
                return ResourceManager.GetString("Brick_WhenIReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when program starts.
        /// </summary>
        public static string Brick_WhenProjectStarts {
            get {
                return ResourceManager.GetString("Brick_WhenProjectStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when tapped.
        /// </summary>
        public static string Brick_WhenTapped {
            get {
                return ResourceManager.GetString("Brick_WhenTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string DefaultProject_Background {
            get {
                return ResourceManager.GetString("DefaultProject_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string DefaultProject_Cat {
            get {
                return ResourceManager.GetString("DefaultProject_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string DefaultProject_Cloud {
            get {
                return ResourceManager.GetString("DefaultProject_Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain drop.
        /// </summary>
        public static string DefaultProject_Rain {
            get {
                return ResourceManager.GetString("DefaultProject_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string DefaultProject_Sun {
            get {
                return ResourceManager.GetString("DefaultProject_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string DefaultProject_Water {
            get {
                return ResourceManager.GetString("DefaultProject_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string Editor_ActionPlural {
            get {
                return ResourceManager.GetString("Editor_ActionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string Editor_ActionSingular {
            get {
                return ResourceManager.GetString("Editor_ActionSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Editor_AppbarAdd {
            get {
                return ResourceManager.GetString("Editor_AppbarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast message.
        /// </summary>
        public static string Editor_BroadcastMessage {
            get {
                return ResourceManager.GetString("Editor_BroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new look.
        /// </summary>
        public static string Editor_ButtonAddCostume {
            get {
                return ResourceManager.GetString("Editor_ButtonAddCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add program variable.
        /// </summary>
        public static string Editor_ButtonAddGlobalVariable {
            get {
                return ResourceManager.GetString("Editor_ButtonAddGlobalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add object variable.
        /// </summary>
        public static string Editor_ButtonAddLocalVariable {
            get {
                return ResourceManager.GetString("Editor_ButtonAddLocalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new object.
        /// </summary>
        public static string Editor_ButtonAddObject {
            get {
                return ResourceManager.GetString("Editor_ButtonAddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string Editor_ButtonAddScript {
            get {
                return ResourceManager.GetString("Editor_ButtonAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sound.
        /// </summary>
        public static string Editor_ButtonAddSound {
            get {
                return ResourceManager.GetString("Editor_ButtonAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string Editor_ButtonBack {
            get {
                return ResourceManager.GetString("Editor_ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Editor_ButtonCancel {
            get {
                return ResourceManager.GetString("Editor_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string Editor_ButtonChange {
            get {
                return ResourceManager.GetString("Editor_ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Editor_ButtonCopy {
            get {
                return ResourceManager.GetString("Editor_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Editor_ButtonDelete {
            get {
                return ResourceManager.GetString("Editor_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Editor_ButtonEdit {
            get {
                return ResourceManager.GetString("Editor_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Editor_ButtonPlayProject {
            get {
                return ResourceManager.GetString("Editor_ButtonPlayProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Editor_ButtonSave {
            get {
                return ResourceManager.GetString("Editor_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string Editor_ButtonUse {
            get {
                return ResourceManager.GetString("Editor_ButtonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Editor_Camera {
            get {
                return ResourceManager.GetString("Editor_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear selection.
        /// </summary>
        public static string Editor_ClearSelection {
            get {
                return ResourceManager.GetString("Editor_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;+&apos; to add a new action..
        /// </summary>
        public static string Editor_ClickPlusToAddAction {
            get {
                return ResourceManager.GetString("Editor_ClickPlusToAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;+&apos; to add a new look..
        /// </summary>
        public static string Editor_ClickPlusToAddCostume {
            get {
                return ResourceManager.GetString("Editor_ClickPlusToAddCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;+&apos; to add a new sound..
        /// </summary>
        public static string Editor_ClickPlusToAddSound {
            get {
                return ResourceManager.GetString("Editor_ClickPlusToAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;+&apos; to add a new object..
        /// </summary>
        public static string Editor_ClickPlusToAddSprite {
            get {
                return ResourceManager.GetString("Editor_ClickPlusToAddSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look name.
        /// </summary>
        public static string Editor_CostumeName {
            get {
                return ResourceManager.GetString("Editor_CostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks.
        /// </summary>
        public static string Editor_CostumePlural {
            get {
                return ResourceManager.GetString("Editor_CostumePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look.
        /// </summary>
        public static string Editor_CostumeSingular {
            get {
                return ResourceManager.GetString("Editor_CostumeSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Editor_Description {
            get {
                return ResourceManager.GetString("Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Editor_GlobalVariables {
            get {
                return ResourceManager.GetString("Editor_GlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Editor_Image {
            get {
                return ResourceManager.GetString("Editor_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string Editor_ImageEditingProgram {
            get {
                return ResourceManager.GetString("Editor_ImageEditingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Editor_ImageGallery {
            get {
                return ResourceManager.GetString("Editor_ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full size.
        /// </summary>
        public static string Editor_ImageSizeFullSize {
            get {
                return ResourceManager.GetString("Editor_ImageSizeFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string Editor_ImageSizeLarge {
            get {
                return ResourceManager.GetString("Editor_ImageSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Editor_ImageSizeMedium {
            get {
                return ResourceManager.GetString("Editor_ImageSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small.
        /// </summary>
        public static string Editor_ImageSizeSmall {
            get {
                return ResourceManager.GetString("Editor_ImageSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Editor_LocalVariables {
            get {
                return ResourceManager.GetString("Editor_LocalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Library.
        /// </summary>
        public static string Editor_MediaLibrary {
            get {
                return ResourceManager.GetString("Editor_MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program settings.
        /// </summary>
        public static string Editor_MenuProjectSettings {
            get {
                return ResourceManager.GetString("Editor_MenuProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start site.
        /// </summary>
        public static string Editor_MenuStartSite {
            get {
                return ResourceManager.GetString("Editor_MenuStartSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Editor_MessageBoxDeleteHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected {1}?.
        /// </summary>
        public static string Editor_MessageBoxDeleteText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceImageHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the image cannot be saved..
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceImageText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceSoundHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceSoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the sound cannot be saved..
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceSoundText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported format.
        /// </summary>
        public static string Editor_MessageBoxWrongImageFormatHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxWrongImageFormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the image has a not supported format..
        /// </summary>
        public static string Editor_MessageBoxWrongImageFormatText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxWrongImageFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Editor_NameOfSound {
            get {
                return ResourceManager.GetString("Editor_NameOfSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No look selected.
        /// </summary>
        public static string Editor_NoCostumeSelected {
            get {
                return ResourceManager.GetString("Editor_NoCostumeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message selected.
        /// </summary>
        public static string Editor_NoMessageSelected {
            get {
                return ResourceManager.GetString("Editor_NoMessageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound selected.
        /// </summary>
        public static string Editor_NoSoundSelected {
            get {
                return ResourceManager.GetString("Editor_NoSoundSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object selected.
        /// </summary>
        public static string Editor_NoSpriteSelected {
            get {
                return ResourceManager.GetString("Editor_NoSpriteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing....
        /// </summary>
        public static string Editor_NothingItem {
            get {
                return ResourceManager.GetString("Editor_NothingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string Editor_NoVariableSelected {
            get {
                return ResourceManager.GetString("Editor_NoVariableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        public static string Editor_ObjectPlural {
            get {
                return ResourceManager.GetString("Editor_ObjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        public static string Editor_ObjectSingular {
            get {
                return ResourceManager.GetString("Editor_ObjectSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Editor_PivotActions {
            get {
                return ResourceManager.GetString("Editor_PivotActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks.
        /// </summary>
        public static string Editor_PivotCostumes {
            get {
                return ResourceManager.GetString("Editor_PivotCostumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Editor_PivotObjects {
            get {
                return ResourceManager.GetString("Editor_PivotObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Editor_PivotSounds {
            get {
                return ResourceManager.GetString("Editor_PivotSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing program.
        /// </summary>
        public static string Editor_PreparingProject {
            get {
                return ResourceManager.GetString("Editor_PreparingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name.
        /// </summary>
        public static string Editor_ProjectName {
            get {
                return ResourceManager.GetString("Editor_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;back&quot; again to dismiss your changes?.
        /// </summary>
        public static string Editor_ReallyDismissFormula {
            get {
                return ResourceManager.GetString("Editor_ReallyDismissFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded.
        /// </summary>
        public static string Editor_Recorded {
            get {
                return ResourceManager.GetString("Editor_Recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        public static string Editor_Recorder {
            get {
                return ResourceManager.GetString("Editor_Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec.
        /// </summary>
        public static string Editor_RecorderRecord {
            get {
                return ResourceManager.GetString("Editor_RecorderRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Editor_RecorderRecordTime {
            get {
                return ResourceManager.GetString("Editor_RecorderRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start recording.
        /// </summary>
        public static string Editor_RecorderStart {
            get {
                return ResourceManager.GetString("Editor_RecorderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Editor_RecorderStop {
            get {
                return ResourceManager.GetString("Editor_RecorderStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string Editor_Rename {
            get {
                return ResourceManager.GetString("Editor_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize image.
        /// </summary>
        public static string Editor_ResizeImage {
            get {
                return ResourceManager.GetString("Editor_ResizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image....
        /// </summary>
        public static string Editor_SavingImage {
            get {
                return ResourceManager.GetString("Editor_SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string Editor_Sec {
            get {
                return ResourceManager.GetString("Editor_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string Editor_Selected {
            get {
                return ResourceManager.GetString("Editor_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading object.
        /// </summary>
        public static string Editor_SelectingObject {
            get {
                return ResourceManager.GetString("Editor_SelectingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT VARIABLE.
        /// </summary>
        public static string Editor_SelectVariablesViewHeader {
            get {
                return ResourceManager.GetString("Editor_SelectVariablesViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound name.
        /// </summary>
        public static string Editor_SoundName {
            get {
                return ResourceManager.GetString("Editor_SoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sounds.
        /// </summary>
        public static string Editor_SoundPlural {
            get {
                return ResourceManager.GetString("Editor_SoundPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        public static string Editor_SoundSingular {
            get {
                return ResourceManager.GetString("Editor_SoundSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        public static string Editor_SpriteName {
            get {
                return ResourceManager.GetString("Editor_SpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramVariable.
        /// </summary>
        public static string Editor_StandardGlobalVariableName {
            get {
                return ResourceManager.GetString("Editor_StandardGlobalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectVariable.
        /// </summary>
        public static string Editor_StandardLocalVariableName {
            get {
                return ResourceManager.GetString("Editor_StandardLocalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE LOOK NAME.
        /// </summary>
        public static string Editor_TitleChangeCostumeName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE SOUND NAME.
        /// </summary>
        public static string Editor_TitleChangeSoundName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE OBJECT NAME.
        /// </summary>
        public static string Editor_TitleChangeSpriteName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeSpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChangeVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE BRICK.
        /// </summary>
        public static string Editor_TitleChooseBrick {
            get {
                return ResourceManager.GetString("Editor_TitleChooseBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE CATEGORY.
        /// </summary>
        public static string Editor_TitleChooseCategory {
            get {
                return ResourceManager.GetString("Editor_TitleChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE LOOK NAME.
        /// </summary>
        public static string Editor_TitleChooseCostumeName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE PROGRAM VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChooseGlobalVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseGlobalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE OBJECT VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChooseLocalVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseLocalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND.
        /// </summary>
        public static string Editor_TitleChooseSound {
            get {
                return ResourceManager.GetString("Editor_TitleChooseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND NAME.
        /// </summary>
        public static string Editor_TitleChooseSoundName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW ACTION.
        /// </summary>
        public static string Editor_TitleNewAction {
            get {
                return ResourceManager.GetString("Editor_TitleNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW BROADCAST MESSAGE.
        /// </summary>
        public static string Editor_TitleNewBroadcastMessage {
            get {
                return ResourceManager.GetString("Editor_TitleNewBroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW LOOK.
        /// </summary>
        public static string Editor_TitleNewCostume {
            get {
                return ResourceManager.GetString("Editor_TitleNewCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SOUND.
        /// </summary>
        public static string Editor_TitleNewSound {
            get {
                return ResourceManager.GetString("Editor_TitleNewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW OBJECT.
        /// </summary>
        public static string Editor_TitleNewSprite {
            get {
                return ResourceManager.GetString("Editor_TitleNewSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM SETTINGS.
        /// </summary>
        public static string Editor_TitleProjectSettings {
            get {
                return ResourceManager.GetString("Editor_TitleProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD SOUND.
        /// </summary>
        public static string Editor_TitleRecorder {
            get {
                return ResourceManager.GetString("Editor_TitleRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something.
        /// </summary>
        public static string Editor_TypeSomething {
            get {
                return ResourceManager.GetString("Editor_TypeSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to SkyDrive.
        /// </summary>
        public static string Editor_UploadToSkyDrive {
            get {
                return ResourceManager.GetString("Editor_UploadToSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name.
        /// </summary>
        public static string Editor_VariableName {
            get {
                return ResourceManager.GetString("Editor_VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        public static string Formula_Constant_False {
            get {
                return ResourceManager.GetString("Formula_Constant_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        public static string Formula_Constant_True {
            get {
                return ResourceManager.GetString("Formula_Constant_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        public static string Formula_Function_Abs {
            get {
                return ResourceManager.GetString("Formula_Function_Abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string Formula_Function_Max {
            get {
                return ResourceManager.GetString("Formula_Function_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Formula_Function_Min {
            get {
                return ResourceManager.GetString("Formula_Function_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string Formula_Function_Random {
            get {
                return ResourceManager.GetString("Formula_Function_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        public static string Formula_Function_Round {
            get {
                return ResourceManager.GetString("Formula_Function_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        public static string Formula_Function_Sqrt {
            get {
                return ResourceManager.GetString("Formula_Function_Sqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string Formula_Operator_And {
            get {
                return ResourceManager.GetString("Formula_Operator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        public static string Formula_Operator_Mod {
            get {
                return ResourceManager.GetString("Formula_Operator_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        public static string Formula_Operator_Not {
            get {
                return ResourceManager.GetString("Formula_Operator_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Formula_Operator_Or {
            get {
                return ResourceManager.GetString("Formula_Operator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brightness.
        /// </summary>
        public static string Formula_Property_Brightness {
            get {
                return ResourceManager.GetString("Formula_Property_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        public static string Formula_Property_Layer {
            get {
                return ResourceManager.GetString("Formula_Property_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.X.
        /// </summary>
        public static string Formula_Property_PositionX {
            get {
                return ResourceManager.GetString("Formula_Property_PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.Y.
        /// </summary>
        public static string Formula_Property_PositionY {
            get {
                return ResourceManager.GetString("Formula_Property_PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation.
        /// </summary>
        public static string Formula_Property_Rotation {
            get {
                return ResourceManager.GetString("Formula_Property_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string Formula_Property_Size {
            get {
                return ResourceManager.GetString("Formula_Property_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparency.
        /// </summary>
        public static string Formula_Property_Transparency {
            get {
                return ResourceManager.GetString("Formula_Property_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration.X.
        /// </summary>
        public static string Formula_Sensor_AccelerationX {
            get {
                return ResourceManager.GetString("Formula_Sensor_AccelerationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration.Y.
        /// </summary>
        public static string Formula_Sensor_AccelerationY {
            get {
                return ResourceManager.GetString("Formula_Sensor_AccelerationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration.Z.
        /// </summary>
        public static string Formula_Sensor_AccelerationZ {
            get {
                return ResourceManager.GetString("Formula_Sensor_AccelerationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compass.
        /// </summary>
        public static string Formula_Sensor_Compass {
            get {
                return ResourceManager.GetString("Formula_Sensor_Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclination.X.
        /// </summary>
        public static string Formula_Sensor_InclinationX {
            get {
                return ResourceManager.GetString("Formula_Sensor_InclinationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclination.Y.
        /// </summary>
        public static string Formula_Sensor_InclinationY {
            get {
                return ResourceManager.GetString("Formula_Sensor_InclinationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loudness.
        /// </summary>
        public static string Formula_Sensor_Loudness {
            get {
                return ResourceManager.GetString("Formula_Sensor_Loudness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comma or times sign..
        /// </summary>
        public static string FormulaInterpreter_Brackets_ArgumentDoubleValue {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_ArgumentDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_EmptyArgument {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_EmptyParentheses {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_EmptyParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the comma. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_NonArgumentParameterSeparator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_NonArgumentParameterSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comma. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_TooFewArguments {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_TooFewArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the superfluous argument(s). .
        /// </summary>
        public static string FormulaInterpreter_Brackets_TooManyArguments {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the unmatched closing parenthesis. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_UnmatchedClosingParenthesis {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_UnmatchedClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the missing closing parenthesis. .
        /// </summary>
        public static string FormulaInterpreter_Brackets_UnmatchedOpeningParenthesis {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Brackets_UnmatchedOpeningParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a times sign. .
        /// </summary>
        public static string FormulaInterpreter_DoubleValue {
            get {
                return ResourceManager.GetString("FormulaInterpreter_DoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an opening parenthesis..
        /// </summary>
        public static string FormulaInterpreter_Function_Empty {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Function_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_NullOrEmpty {
            get {
                return ResourceManager.GetString("FormulaInterpreter_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the double decimal point. .
        /// </summary>
        public static string FormulaInterpreter_Number_DoubleDecimalSeparator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Number_DoubleDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is too large. .
        /// </summary>
        public static string FormulaInterpreter_Number_Overflow {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Number_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the decimal point. .
        /// </summary>
        public static string FormulaInterpreter_Number_SingleDecimalSeparator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Number_SingleDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_Operator_EmptyPrefixOperator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Operator_EmptyPrefixOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_Operator_LeftEmptyInfixOperator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Operator_LeftEmptyInfixOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something. .
        /// </summary>
        public static string FormulaInterpreter_Operator_RightEmptyInfixOperator {
            get {
                return ResourceManager.GetString("FormulaInterpreter_Operator_RightEmptyInfixOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Code for Windows Phone is an on-device visual programming system for the Catrobat programming language..
        /// </summary>
        public static string Main_AboutText {
            get {
                return ResourceManager.GetString("Main_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string Main_ActiveProject {
            get {
                return ResourceManager.GetString("Main_ActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Code for Windows v{0}.
        /// </summary>
        public static string Main_ApplicationNameAndVersion {
            get {
                return ResourceManager.GetString("Main_ApplicationNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Main_ButtonCancel {
            get {
                return ResourceManager.GetString("Main_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Main_ButtonCopy {
            get {
                return ResourceManager.GetString("Main_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string Main_ButtonCreate {
            get {
                return ResourceManager.GetString("Main_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Main_ButtonDelete {
            get {
                return ResourceManager.GetString("Main_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Main_ButtonEdit {
            get {
                return ResourceManager.GetString("Main_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Register.
        /// </summary>
        public static string Main_ButtonLoginRegister {
            get {
                return ResourceManager.GetString("Main_ButtonLoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password forgotten.
        /// </summary>
        public static string Main_ButtonPasswordForgotten {
            get {
                return ResourceManager.GetString("Main_ButtonPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Main_ButtonSave {
            get {
                return ResourceManager.GetString("Main_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string Main_ButtonUpload {
            get {
                return ResourceManager.GetString("Main_ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change name and description.
        /// </summary>
        public static string Main_ChangeProjectNameAndDescription {
            get {
                return ResourceManager.GetString("Main_ChangeProjectNameAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Main_CopyProject {
            get {
                return ResourceManager.GetString("Main_CopyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show memory usage.
        /// </summary>
        public static string Main_DEBUGShowMemory {
            get {
                return ResourceManager.GetString("Main_DEBUGShowMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Program.
        /// </summary>
        public static string Main_DefaultProjectName {
            get {
                return ResourceManager.GetString("Main_DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Main_DeleteProject {
            get {
                return ResourceManager.GetString("Main_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program you chose is being downloaded..
        /// </summary>
        public static string Main_DownloadQueueMessage {
            get {
                return ResourceManager.GetString("Main_DownloadQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string Main_FilterTextBoxHint {
            get {
                return ResourceManager.GetString("Main_FilterTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_HeaderAbout {
            get {
                return ResourceManager.GetString("Main_HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active program.
        /// </summary>
        public static string Main_HeaderCurrentProject {
            get {
                return ResourceManager.GetString("Main_HeaderCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Main_HeaderDesign {
            get {
                return ResourceManager.GetString("Main_HeaderDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Main_HeaderLanguage {
            get {
                return ResourceManager.GetString("Main_HeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My programs.
        /// </summary>
        public static string Main_HeaderLocalProjects {
            get {
                return ResourceManager.GetString("Main_HeaderLocalProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Main_HeaderOnlineProjects {
            get {
                return ResourceManager.GetString("Main_HeaderOnlineProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_HeaderSettings {
            get {
                return ResourceManager.GetString("Main_HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Main_ListDesign {
            get {
                return ResourceManager.GetString("Main_ListDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Main_ListLanguage {
            get {
                return ResourceManager.GetString("Main_ListLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to copy &quot;{0}&quot;?.
        /// </summary>
        public static string Main_MainCopyProjectDialogMessage {
            get {
                return ResourceManager.GetString("Main_MainCopyProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy program?.
        /// </summary>
        public static string Main_MainCopyProjectDialogTitle {
            get {
                return ResourceManager.GetString("Main_MainCopyProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Main_MainDeleteProjectDialogMessage {
            get {
                return ResourceManager.GetString("Main_MainDeleteProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete program?.
        /// </summary>
        public static string Main_MainDeleteProjectDialogTitle {
            get {
                return ResourceManager.GetString("Main_MainDeleteProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Main_MessageBoxInformation {
            get {
                return ResourceManager.GetString("Main_MessageBoxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All downloads finished..
        /// </summary>
        public static string Main_NoDownloadsPending {
            get {
                return ResourceManager.GetString("Main_NoDownloadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All uploads finished..
        /// </summary>
        public static string Main_NoUploadsPending {
            get {
                return ResourceManager.GetString("Main_NoUploadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description:.
        /// </summary>
        public static string Main_OnlineProjectDescription {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Main_OnlineProjectDownloadButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downloads.
        /// </summary>
        public static string Main_OnlineProjectDownloads {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Main_OnlineProjectLicenseButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectLicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string Main_OnlineProjectListBoxLoadMore {
            get {
                return ResourceManager.GetString("Main_OnlineProjectListBoxLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program:.
        /// </summary>
        public static string Main_OnlineProjectProject {
            get {
                return ResourceManager.GetString("Main_OnlineProjectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as unappropriate.
        /// </summary>
        public static string Main_OnlineProjectReportButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics:.
        /// </summary>
        public static string Main_OnlineProjectStatistics {
            get {
                return ResourceManager.GetString("Main_OnlineProjectStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded.
        /// </summary>
        public static string Main_OnlineProjectUploaded {
            get {
                return ResourceManager.GetString("Main_OnlineProjectUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by:.
        /// </summary>
        public static string Main_OnlineProjectUploadedBy {
            get {
                return ResourceManager.GetString("Main_OnlineProjectUploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (version: {0}).
        /// </summary>
        public static string Main_OnlineProjectVersion {
            get {
                return ResourceManager.GetString("Main_OnlineProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} views.
        /// </summary>
        public static string Main_OnlineProjectViews {
            get {
                return ResourceManager.GetString("Main_OnlineProjectViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string Main_PinProjectToStart {
            get {
                return ResourceManager.GetString("Main_PinProjectToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program does not exist.
        /// </summary>
        public static string Main_ProjectDoesNotExist {
            get {
                return ResourceManager.GetString("Main_ProjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, while the program is being activated..
        /// </summary>
        public static string Main_ProjectGettingActivated {
            get {
                return ResourceManager.GetString("Main_ProjectGettingActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name.
        /// </summary>
        public static string Main_ProjectName {
            get {
                return ResourceManager.GetString("Main_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program not valid..
        /// </summary>
        public static string Main_ProjectNotValid {
            get {
                return ResourceManager.GetString("Main_ProjectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;back&quot; again to close the app?.
        /// </summary>
        public static string Main_ReallyCloseApplicationText {
            get {
                return ResourceManager.GetString("Main_ReallyCloseApplicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The selected program could not be opened..
        /// </summary>
        public static string Main_SelectedProjectNotValidHeader {
            get {
                return ResourceManager.GetString("Main_SelectedProjectNotValidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program not valid.
        /// </summary>
        public static string Main_SelectedProjectNotValidMessage {
            get {
                return ResourceManager.GetString("Main_SelectedProjectNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set active.
        /// </summary>
        public static string Main_SetActive {
            get {
                return ResourceManager.GetString("Main_SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable/disable bricks.
        /// </summary>
        public static string Main_SettingsBricks {
            get {
                return ResourceManager.GetString("Main_SettingsBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mindstorm bricks.
        /// </summary>
        public static string Main_SettingsEnableNXTBricks {
            get {
                return ResourceManager.GetString("Main_SettingsEnableNXTBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Main_SettingsTheme {
            get {
                return ResourceManager.GetString("Main_SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string Main_ShareProject {
            get {
                return ResourceManager.GetString("Main_ShareProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PROGRAM.
        /// </summary>
        public static string Main_TitleNewProject {
            get {
                return ResourceManager.GetString("Main_TitleNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Main_TitleSettings {
            get {
                return ResourceManager.GetString("Main_TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD PROGRAM.
        /// </summary>
        public static string Main_TitleUploadProject {
            get {
                return ResourceManager.GetString("Main_TitleUploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN OR REGISTER.
        /// </summary>
        public static string Main_TitleUploadProjectLogin {
            get {
                return ResourceManager.GetString("Main_TitleUploadProjectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Main_UploadProjectEmail {
            get {
                return ResourceManager.GetString("Main_UploadProjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your login state is beeing checked!.
        /// </summary>
        public static string Main_UploadProjectLoadingMessage {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error. {0}.
        /// </summary>
        public static string Main_UploadProjectLoginError {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string Main_UploadProjectLoginErrorCaption {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoginErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login- or registrationdata is incomplete..
        /// </summary>
        public static string Main_UploadProjectMissingLoginData {
            get {
                return ResourceManager.GetString("Main_UploadProjectMissingLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Main_UploadProjectPassword {
            get {
                return ResourceManager.GetString("Main_UploadProjectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Main_UploadProjectProjectDescription {
            get {
                return ResourceManager.GetString("Main_UploadProjectProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program:.
        /// </summary>
        public static string Main_UploadProjectProjectName {
            get {
                return ResourceManager.GetString("Main_UploadProjectProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful!.
        /// </summary>
        public static string Main_UploadProjectRegistrationSucessful {
            get {
                return ResourceManager.GetString("Main_UploadProjectRegistrationSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error. Error code {0}.
        /// </summary>
        public static string Main_UploadProjectUndefinedError {
            get {
                return ResourceManager.GetString("Main_UploadProjectUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Main_UploadProjectUsername {
            get {
                return ResourceManager.GetString("Main_UploadProjectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string Main_UploadProjectWelcome {
            get {
                return ResourceManager.GetString("Main_UploadProjectWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your program is being uploaded. This might take a little while, but we&apos;ll tell you when it&apos;s finished!.
        /// </summary>
        public static string Main_UploadQueueMessage {
            get {
                return ResourceManager.GetString("Main_UploadQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current program ({0}) as template?.
        /// </summary>
        public static string Main_UseCurrentProjectAsTemplate {
            get {
                return ResourceManager.GetString("Main_UseCurrentProjectAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program version is not supported..
        /// </summary>
        public static string Main_VersionIsNotSupported {
            get {
                return ResourceManager.GetString("Main_VersionIsNotSupported", resourceCulture);
            }
        }
    }
}
