//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.Core.Resources.ApplicationResources", typeof(ApplicationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroidtest.ist.tugraz.at/api/checkTokenOrRegister/check.json.
        /// </summary>
        public static string CheckTokenOrRegisterUrl {
            get {
                return ResourceManager.GetString("CheckTokenOrRegisterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroidtest.ist.tugraz.at/api/checkToken/check.json.
        /// </summary>
        public static string CheckTokenUrl {
            get {
                return ResourceManager.GetString("CheckTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .catrobat.
        /// </summary>
        public static string EXTENSION {
            get {
                return ResourceManager.GetString("EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string FILE_UPLOAD_TAG {
            get {
                return ResourceManager.GetString("FILE_UPLOAD_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string MIMETYPE {
            get {
                return ResourceManager.GetString("MIMETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroidtest.ist.tugraz.at/api/projects/search.xml?limit=5&amp;offset={0}&amp;query={1}.
        /// </summary>
        public static string OnlineFilterUrl {
            get {
                return ResourceManager.GetString("OnlineFilterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroidtest.ist.tugraz.at/api/projects/recent.xml?limit=5&amp;offset={0}.
        /// </summary>
        public static string OnlineRecentUrl {
            get {
                return ResourceManager.GetString("OnlineRecentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileChecksum.
        /// </summary>
        public static string PROJECT_CHECKSUM_TAG {
            get {
                return ResourceManager.GetString("PROJECT_CHECKSUM_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectDescription.
        /// </summary>
        public static string PROJECT_DESCRIPTION_TAG {
            get {
                return ResourceManager.GetString("PROJECT_DESCRIPTION_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectTitle.
        /// </summary>
        public static string PROJECT_NAME_TAG {
            get {
                return ResourceManager.GetString("PROJECT_NAME_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroid.org/catroid/projectlicense.
        /// </summary>
        public static string ProjectLicenseUrl {
            get {
                return ResourceManager.GetString("ProjectLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationCountry.
        /// </summary>
        public static string REG_USER_COUNTRY {
            get {
                return ResourceManager.GetString("REG_USER_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationEmail.
        /// </summary>
        public static string REG_USER_EMAIL {
            get {
                return ResourceManager.GetString("REG_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationLanguage.
        /// </summary>
        public static string REG_USER_LANGUAGE {
            get {
                return ResourceManager.GetString("REG_USER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationUsername.
        /// </summary>
        public static string REG_USER_NAME {
            get {
                return ResourceManager.GetString("REG_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationPassword.
        /// </summary>
        public static string REG_USER_PASSWORD {
            get {
                return ResourceManager.GetString("REG_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string TOKEN {
            get {
                return ResourceManager.GetString("TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catroidtest.ist.tugraz.at/api/upload/upload.json.
        /// </summary>
        public static string UploadFileUrl {
            get {
                return ResourceManager.GetString("UploadFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userEmail.
        /// </summary>
        public static string USER_EMAIL {
            get {
                return ResourceManager.GetString("USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userLanguage.
        /// </summary>
        public static string USER_LANGUAGE {
            get {
                return ResourceManager.GetString("USER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone 7 Device.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
