//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/08/2016 11:32:54
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Catrobat.Core.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class ApplicationResources
    {
        
        private static ResourceLoader resourceLoader;
        
        static ApplicationResources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ApplicationResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("ApplicationResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/ApplicationResources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "https://catroid-test.catrob.at/api/"
        /// </summary>
        public static string API_BASE_ADDRESS
        {
            get
            {
                return resourceLoader.GetString("API_BASE_ADDRESS");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "checkToken/check.json"
        /// </summary>
        public static string API_CHECK_TOKEN
        {
            get
            {
                return resourceLoader.GetString("API_CHECK_TOKEN");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "loginOrRegister/loginOrRegister.json"
        /// </summary>
        public static string API_LOGIN_REGISTER
        {
            get
            {
                return resourceLoader.GetString("API_LOGIN_REGISTER");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "fileChecksum"
        /// </summary>
        public static string API_PARAM_CHECKSUM
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_CHECKSUM");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "flagReason"
        /// </summary>
        public static string API_PARAM_FLAG_REASON
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_FLAG_REASON");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "c"
        /// </summary>
        public static string API_PARAM_HASH
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_HASH");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "userLanguage"
        /// </summary>
        public static string API_PARAM_LANGUAGE
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_LANGUAGE");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "passwordSavePassword"
        /// </summary>
        public static string API_PARAM_NEW_PWD
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_NEW_PWD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "passwordSavePassword2"
        /// </summary>
        public static string API_PARAM_NEW_PWD_REPEAT
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_NEW_PWD_REPEAT");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "projectId"
        /// </summary>
        public static string API_PARAM_PROJECTID
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_PROJECTID");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "passwordRecoveryUserdata"
        /// </summary>
        public static string API_PARAM_RECOVER_PWD
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_RECOVER_PWD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "registrationCountry"
        /// </summary>
        public static string API_PARAM_REG_COUNTRY
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_REG_COUNTRY");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "registrationEmail"
        /// </summary>
        public static string API_PARAM_REG_EMAIL
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_REG_EMAIL");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "registrationPassword"
        /// </summary>
        public static string API_PARAM_REG_PASSWORD
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_REG_PASSWORD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "registrationUsername"
        /// </summary>
        public static string API_PARAM_REG_USERNAME
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_REG_USERNAME");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "token"
        /// </summary>
        public static string API_PARAM_TOKEN
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_TOKEN");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "upload"
        /// </summary>
        public static string API_PARAM_UPLOAD
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_UPLOAD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "username"
        /// </summary>
        public static string API_PARAM_USERNAME
        {
            get
            {
                return resourceLoader.GetString("API_PARAM_USERNAME");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "projects/recent.json?limit={0}&offset={1}"
        /// </summary>
        public static string API_RECENT_PROJECTS
        {
            get
            {
                return resourceLoader.GetString("API_RECENT_PROJECTS");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "4"
        /// </summary>
        public static string API_REQUEST_LIMIT
        {
            get
            {
                return resourceLoader.GetString("API_REQUEST_LIMIT");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "projects/search.json?query={0}&limit={1}&offset={2}"
        /// </summary>
        public static string API_SEARCH_PROJECTS
        {
            get
            {
                return resourceLoader.GetString("API_SEARCH_PROJECTS");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "upload/upload.json"
        /// </summary>
        public static string API_UPLOAD
        {
            get
            {
                return resourceLoader.GetString("API_UPLOAD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "http://developer.catrobat.org/licenses"
        /// </summary>
        public static string CATROBAT_LICENSES_URL
        {
            get
            {
                return resourceLoader.GetString("CATROBAT_LICENSES_URL");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "http://catrob.at/tou"
        /// </summary>
        public static string CATROBAT_TOU_URL
        {
            get
            {
                return resourceLoader.GetString("CATROBAT_TOU_URL");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "http://www.catrobat.org/"
        /// </summary>
        public static string CATROBAT_URL
        {
            get
            {
                return resourceLoader.GetString("CATROBAT_URL");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "passwordrecovery/changeMyPasswordRequest.json"
        /// </summary>
        public static string CATROWEB_CHANGE_PWD
        {
            get
            {
                return resourceLoader.GetString("CATROWEB_CHANGE_PWD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "passwordrecovery/sendMailRequest.json"
        /// </summary>
        public static string CATROWEB_RECOVER_PWD
        {
            get
            {
                return resourceLoader.GetString("CATROWEB_RECOVER_PWD");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "flagInappropriate/flag.json"
        /// </summary>
        public static string CATROWEB_REPORT_AS_INAPPROPRIATE
        {
            get
            {
                return resourceLoader.GetString("CATROWEB_REPORT_AS_INAPPROPRIATE");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ".catrobat"
        /// </summary>
        public static string EXTENSION
        {
            get
            {
                return resourceLoader.GetString("EXTENSION");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "application/octet-stream"
        /// </summary>
        public static string MIMETYPE
        {
            get
            {
                return resourceLoader.GetString("MIMETYPE");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "https://share.catrob.at/"
        /// </summary>
        public static string POCEKTCODE_BASE_ADDRESS
        {
            get
            {
                return resourceLoader.GetString("POCEKTCODE_BASE_ADDRESS");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "https://pocketcode.org/licenseToPlay"
        /// </summary>
        public static string PROJECT_LICENSE_URL
        {
            get
            {
                return resourceLoader.GetString("PROJECT_LICENSE_URL");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "userEmail"
        /// </summary>
        public static string USER_EMAIL
        {
            get
            {
                return resourceLoader.GetString("USER_EMAIL");
            }
        }
    }
}
