//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.33440
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDE.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDE.Core.Resources.ApplicationResources", typeof(ApplicationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://pocketcode.org/api/ ähnelt.
        /// </summary>
        public static string API_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("API_BASE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checkToken/check.json ähnelt.
        /// </summary>
        public static string API_CHECK_TOKEN {
            get {
                return ResourceManager.GetString("API_CHECK_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loginOrRegister/loginOrRegister.json ähnelt.
        /// </summary>
        public static string API_LOGIN_REGISTER {
            get {
                return ResourceManager.GetString("API_LOGIN_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fileChecksum ähnelt.
        /// </summary>
        public static string API_PARAM_CHECKSUM {
            get {
                return ResourceManager.GetString("API_PARAM_CHECKSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die flagReason ähnelt.
        /// </summary>
        public static string API_PARAM_FLAG_REASON {
            get {
                return ResourceManager.GetString("API_PARAM_FLAG_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die c ähnelt.
        /// </summary>
        public static string API_PARAM_HASH {
            get {
                return ResourceManager.GetString("API_PARAM_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die userLanguage ähnelt.
        /// </summary>
        public static string API_PARAM_LANGUAGE {
            get {
                return ResourceManager.GetString("API_PARAM_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die passwordSavePassword ähnelt.
        /// </summary>
        public static string API_PARAM_NEW_PWD {
            get {
                return ResourceManager.GetString("API_PARAM_NEW_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die passwordSavePassword2 ähnelt.
        /// </summary>
        public static string API_PARAM_NEW_PWD_REPEAT {
            get {
                return ResourceManager.GetString("API_PARAM_NEW_PWD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die projectId ähnelt.
        /// </summary>
        public static string API_PARAM_PROJECTID {
            get {
                return ResourceManager.GetString("API_PARAM_PROJECTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die passwordRecoveryUserdata ähnelt.
        /// </summary>
        public static string API_PARAM_RECOVER_PWD {
            get {
                return ResourceManager.GetString("API_PARAM_RECOVER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die registrationCountry ähnelt.
        /// </summary>
        public static string API_PARAM_REG_COUNTRY {
            get {
                return ResourceManager.GetString("API_PARAM_REG_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die registrationEmail ähnelt.
        /// </summary>
        public static string API_PARAM_REG_EMAIL {
            get {
                return ResourceManager.GetString("API_PARAM_REG_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die registrationPassword ähnelt.
        /// </summary>
        public static string API_PARAM_REG_PASSWORD {
            get {
                return ResourceManager.GetString("API_PARAM_REG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die registrationUsername ähnelt.
        /// </summary>
        public static string API_PARAM_REG_USERNAME {
            get {
                return ResourceManager.GetString("API_PARAM_REG_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die token ähnelt.
        /// </summary>
        public static string API_PARAM_TOKEN {
            get {
                return ResourceManager.GetString("API_PARAM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die upload ähnelt.
        /// </summary>
        public static string API_PARAM_UPLOAD {
            get {
                return ResourceManager.GetString("API_PARAM_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die username ähnelt.
        /// </summary>
        public static string API_PARAM_USERNAME {
            get {
                return ResourceManager.GetString("API_PARAM_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die projects/recent.json?limit={0}&amp;offset={1} ähnelt.
        /// </summary>
        public static string API_RECENT_PROJECTS {
            get {
                return ResourceManager.GetString("API_RECENT_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 ähnelt.
        /// </summary>
        public static string API_REQUEST_LIMIT {
            get {
                return ResourceManager.GetString("API_REQUEST_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die projects/search.json?query={0}&amp;limit={1}&amp;offset={2} ähnelt.
        /// </summary>
        public static string API_SEARCH_PROJECTS {
            get {
                return ResourceManager.GetString("API_SEARCH_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die upload/upload.json ähnelt.
        /// </summary>
        public static string API_UPLOAD {
            get {
                return ResourceManager.GetString("API_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://developer.catrobat.org/licenses ähnelt.
        /// </summary>
        public static string CATROBAT_LICENSES_URL {
            get {
                return ResourceManager.GetString("CATROBAT_LICENSES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.catrobat.org/ ähnelt.
        /// </summary>
        public static string CATROBAT_URL {
            get {
                return ResourceManager.GetString("CATROBAT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die passwordrecovery/changeMyPasswordRequest.json ähnelt.
        /// </summary>
        public static string CATROWEB_CHANGE_PWD {
            get {
                return ResourceManager.GetString("CATROWEB_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die passwordrecovery/sendMailRequest.json ähnelt.
        /// </summary>
        public static string CATROWEB_RECOVER_PWD {
            get {
                return ResourceManager.GetString("CATROWEB_RECOVER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die flagInappropriate/flag.json ähnelt.
        /// </summary>
        public static string CATROWEB_REPORT_AS_INAPPROPRIATE {
            get {
                return ResourceManager.GetString("CATROWEB_REPORT_AS_INAPPROPRIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .catrobat ähnelt.
        /// </summary>
        public static string EXTENSION {
            get {
                return ResourceManager.GetString("EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die application/octet-stream ähnelt.
        /// </summary>
        public static string MIMETYPE {
            get {
                return ResourceManager.GetString("MIMETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://opensource.org/licenses/MS-RL ähnelt.
        /// </summary>
        public static string MS_RL_LICENSE_URL {
            get {
                return ResourceManager.GetString("MS_RL_LICENSE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://pocketcode.org/ ähnelt.
        /// </summary>
        public static string POCEKTCODE_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("POCEKTCODE_BASE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://pocketcode.org/licenseToPlay ähnelt.
        /// </summary>
        public static string PROJECT_LICENSE_URL {
            get {
                return ResourceManager.GetString("PROJECT_LICENSE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die userEmail ähnelt.
        /// </summary>
        public static string USER_EMAIL {
            get {
                return ResourceManager.GetString("USER_EMAIL", resourceCulture);
            }
        }
    }
}
