//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDEWindowsPhone.Content.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDEWindowsPhone.Content.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string App_FlowDirection {
            get {
                return ResourceManager.GetString("App_FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string App_ResourceLanguage {
            get {
                return ResourceManager.GetString("App_ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast.
        /// </summary>
        public static string Brick_Broadcast {
            get {
                return ResourceManager.GetString("Brick_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast and wait.
        /// </summary>
        public static string Brick_BroadcastWait {
            get {
                return ResourceManager.GetString("Brick_BroadcastWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new....
        /// </summary>
        public static string Brick_ButtonNew {
            get {
                return ResourceManager.GetString("Brick_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Brick_CategoryControl {
            get {
                return ResourceManager.GetString("Brick_CategoryControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks.
        /// </summary>
        public static string Brick_CategoryLooks {
            get {
                return ResourceManager.GetString("Brick_CategoryLooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        public static string Brick_CategoryMotion {
            get {
                return ResourceManager.GetString("Brick_CategoryMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Brick_CategorySound {
            get {
                return ResourceManager.GetString("Brick_CategorySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Brick_CategoryVariables {
            get {
                return ResourceManager.GetString("Brick_CategoryVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change brightness by.
        /// </summary>
        public static string Brick_ChangeBrightnessBy {
            get {
                return ResourceManager.GetString("Brick_ChangeBrightnessBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change ghost effect by.
        /// </summary>
        public static string Brick_ChangeGhostEffectBy {
            get {
                return ResourceManager.GetString("Brick_ChangeGhostEffectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change size by.
        /// </summary>
        public static string Brick_ChangeSizeBy {
            get {
                return ResourceManager.GetString("Brick_ChangeSizeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change variable.
        /// </summary>
        public static string Brick_ChangeVariable {
            get {
                return ResourceManager.GetString("Brick_ChangeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Brick_ChangeVariableBy {
            get {
                return ResourceManager.GetString("Brick_ChangeVariableBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change volume by.
        /// </summary>
        public static string Brick_ChangeVolumeBy {
            get {
                return ResourceManager.GetString("Brick_ChangeVolumeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change X by.
        /// </summary>
        public static string Brick_ChangeXBy {
            get {
                return ResourceManager.GetString("Brick_ChangeXBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Y by.
        /// </summary>
        public static string Brick_ChangeYBy {
            get {
                return ResourceManager.GetString("Brick_ChangeYBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear graphic effects.
        /// </summary>
        public static string Brick_ClearGraphicEffects {
            get {
                return ResourceManager.GetString("Brick_ClearGraphicEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to come to front.
        /// </summary>
        public static string Brick_ComeToFront {
            get {
                return ResourceManager.GetString("Brick_ComeToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        public static string Brick_Degrees {
            get {
                return ResourceManager.GetString("Brick_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever.
        /// </summary>
        public static string Brick_Forever {
            get {
                return ResourceManager.GetString("Brick_Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever end.
        /// </summary>
        public static string Brick_ForeverLoopEnd {
            get {
                return ResourceManager.GetString("Brick_ForeverLoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glide.
        /// </summary>
        public static string Brick_GlideToGlide {
            get {
                return ResourceManager.GetString("Brick_GlideToGlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Brick_GlideToTo {
            get {
                return ResourceManager.GetString("Brick_GlideToTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        public static string Brick_GoNStepsBackGo {
            get {
                return ResourceManager.GetString("Brick_GoNStepsBackGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layers.
        /// </summary>
        public static string Brick_GoNStepsBackStepsBack {
            get {
                return ResourceManager.GetString("Brick_GoNStepsBackStepsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string Brick_Hide {
            get {
                return ResourceManager.GetString("Brick_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        public static string Brick_IfLogicBegin {
            get {
                return ResourceManager.GetString("Brick_IfLogicBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true, then.
        /// </summary>
        public static string Brick_IfLogicBeginTrue {
            get {
                return ResourceManager.GetString("Brick_IfLogicBeginTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        public static string Brick_IfLogicElse {
            get {
                return ResourceManager.GetString("Brick_IfLogicElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else end.
        /// </summary>
        public static string Brick_IfLogicEnd {
            get {
                return ResourceManager.GetString("Brick_IfLogicEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if on edge, bounce.
        /// </summary>
        public static string Brick_IfOnEdgeBounce {
            get {
                return ResourceManager.GetString("Brick_IfOnEdgeBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string Brick_MoveNStepsMove {
            get {
                return ResourceManager.GetString("Brick_MoveNStepsMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps.
        /// </summary>
        public static string Brick_MoveNStepsSteps {
            get {
                return ResourceManager.GetString("Brick_MoveNStepsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next costume.
        /// </summary>
        public static string Brick_NextCostume {
            get {
                return ResourceManager.GetString("Brick_NextCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string Brick_Note {
            get {
                return ResourceManager.GetString("Brick_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place at.
        /// </summary>
        public static string Brick_PlaceAt {
            get {
                return ResourceManager.GetString("Brick_PlaceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play sound.
        /// </summary>
        public static string Brick_PlaySound {
            get {
                return ResourceManager.GetString("Brick_PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point in direction.
        /// </summary>
        public static string Brick_PointInDirection {
            get {
                return ResourceManager.GetString("Brick_PointInDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point towards.
        /// </summary>
        public static string Brick_PointTo {
            get {
                return ResourceManager.GetString("Brick_PointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string Brick_Repeat {
            get {
                return ResourceManager.GetString("Brick_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat end.
        /// </summary>
        public static string Brick_RepeatLoopEnd {
            get {
                return ResourceManager.GetString("Brick_RepeatLoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Brick_Seconds {
            get {
                return ResourceManager.GetString("Brick_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set brightness to.
        /// </summary>
        public static string Brick_SetBrightnessTo {
            get {
                return ResourceManager.GetString("Brick_SetBrightnessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set costume.
        /// </summary>
        public static string Brick_SetCostume {
            get {
                return ResourceManager.GetString("Brick_SetCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set ghost effect to.
        /// </summary>
        public static string Brick_SetGhostEffectTo {
            get {
                return ResourceManager.GetString("Brick_SetGhostEffectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set size to.
        /// </summary>
        public static string Brick_SetSizeTo {
            get {
                return ResourceManager.GetString("Brick_SetSizeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Variable.
        /// </summary>
        public static string Brick_SetVariable {
            get {
                return ResourceManager.GetString("Brick_SetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Brick_SetVariableTo {
            get {
                return ResourceManager.GetString("Brick_SetVariableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set volume to.
        /// </summary>
        public static string Brick_SetVolumeTo {
            get {
                return ResourceManager.GetString("Brick_SetVolumeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set X to.
        /// </summary>
        public static string Brick_SetXTo {
            get {
                return ResourceManager.GetString("Brick_SetXTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Y to.
        /// </summary>
        public static string Brick_SetYTo {
            get {
                return ResourceManager.GetString("Brick_SetYTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string Brick_Show {
            get {
                return ResourceManager.GetString("Brick_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speak.
        /// </summary>
        public static string Brick_Speak {
            get {
                return ResourceManager.GetString("Brick_Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop all sounds.
        /// </summary>
        public static string Brick_StopAllSounds {
            get {
                return ResourceManager.GetString("Brick_StopAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string Brick_Times {
            get {
                return ResourceManager.GetString("Brick_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn left.
        /// </summary>
        public static string Brick_TurnLeft {
            get {
                return ResourceManager.GetString("Brick_TurnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn right.
        /// </summary>
        public static string Brick_TurnRight {
            get {
                return ResourceManager.GetString("Brick_TurnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait.
        /// </summary>
        public static string Brick_Wait {
            get {
                return ResourceManager.GetString("Brick_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when I receive.
        /// </summary>
        public static string Brick_WhenIReceive {
            get {
                return ResourceManager.GetString("Brick_WhenIReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when project starts.
        /// </summary>
        public static string Brick_WhenProjectStarts {
            get {
                return ResourceManager.GetString("Brick_WhenProjectStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when tapped.
        /// </summary>
        public static string Brick_WhenTapped {
            get {
                return ResourceManager.GetString("Brick_WhenTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string Editor_ActionPlural {
            get {
                return ResourceManager.GetString("Editor_ActionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string Editor_ActionSingular {
            get {
                return ResourceManager.GetString("Editor_ActionSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Editor_AppbarAdd {
            get {
                return ResourceManager.GetString("Editor_AppbarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast message.
        /// </summary>
        public static string Editor_BroadcastMessage {
            get {
                return ResourceManager.GetString("Editor_BroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new costume.
        /// </summary>
        public static string Editor_ButtonAddCostume {
            get {
                return ResourceManager.GetString("Editor_ButtonAddCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add global variable.
        /// </summary>
        public static string Editor_ButtonAddGlobalVariable {
            get {
                return ResourceManager.GetString("Editor_ButtonAddGlobalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add local variable.
        /// </summary>
        public static string Editor_ButtonAddLocalVariable {
            get {
                return ResourceManager.GetString("Editor_ButtonAddLocalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new object.
        /// </summary>
        public static string Editor_ButtonAddObject {
            get {
                return ResourceManager.GetString("Editor_ButtonAddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string Editor_ButtonAddScript {
            get {
                return ResourceManager.GetString("Editor_ButtonAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sound.
        /// </summary>
        public static string Editor_ButtonAddSound {
            get {
                return ResourceManager.GetString("Editor_ButtonAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string Editor_ButtonBack {
            get {
                return ResourceManager.GetString("Editor_ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Editor_ButtonCancel {
            get {
                return ResourceManager.GetString("Editor_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string Editor_ButtonChange {
            get {
                return ResourceManager.GetString("Editor_ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Editor_ButtonCopy {
            get {
                return ResourceManager.GetString("Editor_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Editor_ButtonDelete {
            get {
                return ResourceManager.GetString("Editor_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play project.
        /// </summary>
        public static string Editor_ButtonPlayProject {
            get {
                return ResourceManager.GetString("Editor_ButtonPlayProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Editor_ButtonSave {
            get {
                return ResourceManager.GetString("Editor_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string Editor_ButtonUse {
            get {
                return ResourceManager.GetString("Editor_ButtonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Editor_Camera {
            get {
                return ResourceManager.GetString("Editor_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string Editor_Camera_Rename {
            get {
                return ResourceManager.GetString("Editor_Camera_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selektierung aufheben.
        /// </summary>
        public static string Editor_ClearSelection {
            get {
                return ResourceManager.GetString("Editor_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume name.
        /// </summary>
        public static string Editor_CostumeName {
            get {
                return ResourceManager.GetString("Editor_CostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costumes.
        /// </summary>
        public static string Editor_CostumePlural {
            get {
                return ResourceManager.GetString("Editor_CostumePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costume.
        /// </summary>
        public static string Editor_CostumeSingular {
            get {
                return ResourceManager.GetString("Editor_CostumeSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Editor_Description {
            get {
                return ResourceManager.GetString("Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Editor_GlobalVariables {
            get {
                return ResourceManager.GetString("Editor_GlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Editor_Image {
            get {
                return ResourceManager.GetString("Editor_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery.
        /// </summary>
        public static string Editor_ImageGallery {
            get {
                return ResourceManager.GetString("Editor_ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full size.
        /// </summary>
        public static string Editor_ImageSizeFullSize {
            get {
                return ResourceManager.GetString("Editor_ImageSizeFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string Editor_ImageSizeLarge {
            get {
                return ResourceManager.GetString("Editor_ImageSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Editor_ImageSizeMedium {
            get {
                return ResourceManager.GetString("Editor_ImageSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small.
        /// </summary>
        public static string Editor_ImageSizeSmall {
            get {
                return ResourceManager.GetString("Editor_ImageSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Editor_LocalVariables {
            get {
                return ResourceManager.GetString("Editor_LocalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Library.
        /// </summary>
        public static string Editor_MediaLibrary {
            get {
                return ResourceManager.GetString("Editor_MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Editor_MenuProjectSettings {
            get {
                return ResourceManager.GetString("Editor_MenuProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start site.
        /// </summary>
        public static string Editor_MenuStartSite {
            get {
                return ResourceManager.GetString("Editor_MenuStartSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Editor_MessageBoxDeleteHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected {1}..
        /// </summary>
        public static string Editor_MessageBoxDeleteText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceImageHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the image cannot be saved..
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceImageText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceSoundHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceSoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without more disc space the sound cannot be saved..
        /// </summary>
        public static string Editor_MessageBoxNotEnoughSpaceSoundText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxNotEnoughSpaceSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported format.
        /// </summary>
        public static string Editor_MessageBoxWrongImageFormatHeader {
            get {
                return ResourceManager.GetString("Editor_MessageBoxWrongImageFormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the image has a not supported format..
        /// </summary>
        public static string Editor_MessageBoxWrongImageFormatText {
            get {
                return ResourceManager.GetString("Editor_MessageBoxWrongImageFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}.
        /// </summary>
        public static string Editor_New {
            get {
                return ResourceManager.GetString("Editor_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action.
        /// </summary>
        public static string Editor_NewAction {
            get {
                return ResourceManager.GetString("Editor_NewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new costume.
        /// </summary>
        public static string Editor_NewCostume {
            get {
                return ResourceManager.GetString("Editor_NewCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new object.
        /// </summary>
        public static string Editor_NewObject {
            get {
                return ResourceManager.GetString("Editor_NewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sound.
        /// </summary>
        public static string Editor_NewSound {
            get {
                return ResourceManager.GetString("Editor_NewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No costume selected.
        /// </summary>
        public static string Editor_NoCostumeSelected {
            get {
                return ResourceManager.GetString("Editor_NoCostumeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message selected.
        /// </summary>
        public static string Editor_NoMessageSelected {
            get {
                return ResourceManager.GetString("Editor_NoMessageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound selected.
        /// </summary>
        public static string Editor_NoSoundSelected {
            get {
                return ResourceManager.GetString("Editor_NoSoundSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object selected.
        /// </summary>
        public static string Editor_NoSpriteSelected {
            get {
                return ResourceManager.GetString("Editor_NoSpriteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing....
        /// </summary>
        public static string Editor_NothingItem {
            get {
                return ResourceManager.GetString("Editor_NothingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string Editor_NoVariableSelected {
            get {
                return ResourceManager.GetString("Editor_NoVariableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        public static string Editor_ObjectPlural {
            get {
                return ResourceManager.GetString("Editor_ObjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        public static string Editor_ObjectSingular {
            get {
                return ResourceManager.GetString("Editor_ObjectSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Editor_PivotActions {
            get {
                return ResourceManager.GetString("Editor_PivotActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costumes.
        /// </summary>
        public static string Editor_PivotCostumes {
            get {
                return ResourceManager.GetString("Editor_PivotCostumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Editor_PivotObjects {
            get {
                return ResourceManager.GetString("Editor_PivotObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Editor_PivotSounds {
            get {
                return ResourceManager.GetString("Editor_PivotSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Editor_ProjectName {
            get {
                return ResourceManager.GetString("Editor_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        public static string Editor_Recorder {
            get {
                return ResourceManager.GetString("Editor_Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec.
        /// </summary>
        public static string Editor_RecorderRecord {
            get {
                return ResourceManager.GetString("Editor_RecorderRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Editor_RecorderRecordTime {
            get {
                return ResourceManager.GetString("Editor_RecorderRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start recording.
        /// </summary>
        public static string Editor_RecorderStart {
            get {
                return ResourceManager.GetString("Editor_RecorderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Editor_RecorderStop {
            get {
                return ResourceManager.GetString("Editor_RecorderStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Editor_Recording {
            get {
                return ResourceManager.GetString("Editor_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving image.
        /// </summary>
        public static string Editor_SavingImage {
            get {
                return ResourceManager.GetString("Editor_SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string Editor_Selected {
            get {
                return ResourceManager.GetString("Editor_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading object.
        /// </summary>
        public static string Editor_SelectingObject {
            get {
                return ResourceManager.GetString("Editor_SelectingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT VARIABLE.
        /// </summary>
        public static string Editor_SelectVariablesViewHeader {
            get {
                return ResourceManager.GetString("Editor_SelectVariablesViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound name.
        /// </summary>
        public static string Editor_SoundName {
            get {
                return ResourceManager.GetString("Editor_SoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sounds.
        /// </summary>
        public static string Editor_SoundPlural {
            get {
                return ResourceManager.GetString("Editor_SoundPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        public static string Editor_SoundSingular {
            get {
                return ResourceManager.GetString("Editor_SoundSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        public static string Editor_SpriteName {
            get {
                return ResourceManager.GetString("Editor_SpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalVariable.
        /// </summary>
        public static string Editor_StandardGlobalVariableName {
            get {
                return ResourceManager.GetString("Editor_StandardGlobalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectVariable.
        /// </summary>
        public static string Editor_StandardLocalVariableName {
            get {
                return ResourceManager.GetString("Editor_StandardLocalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE COSTUME NAME.
        /// </summary>
        public static string Editor_TitleChangeCostumeName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE SOUND NAME.
        /// </summary>
        public static string Editor_TitleChangeSoundName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE OBJECT NAME.
        /// </summary>
        public static string Editor_TitleChangeSpriteName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeSpriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChangeVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChangeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE BRICK.
        /// </summary>
        public static string Editor_TitleChooseBrick {
            get {
                return ResourceManager.GetString("Editor_TitleChooseBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE CATEGORY.
        /// </summary>
        public static string Editor_TitleChooseCategory {
            get {
                return ResourceManager.GetString("Editor_TitleChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE COSTUME NAME.
        /// </summary>
        public static string Editor_TitleChooseCostumeName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseCostumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE GLOBAL VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChooseGlobalVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseGlobalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE OBJECT VARIABLE NAME.
        /// </summary>
        public static string Editor_TitleChooseLocalVariableName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseLocalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND.
        /// </summary>
        public static string Editor_TitleChooseSound {
            get {
                return ResourceManager.GetString("Editor_TitleChooseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE SOUND NAME.
        /// </summary>
        public static string Editor_TitleChooseSoundName {
            get {
                return ResourceManager.GetString("Editor_TitleChooseSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW ACTION.
        /// </summary>
        public static string Editor_TitleNewAction {
            get {
                return ResourceManager.GetString("Editor_TitleNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW BROADCAST MESSAGE.
        /// </summary>
        public static string Editor_TitleNewBroadcastMessage {
            get {
                return ResourceManager.GetString("Editor_TitleNewBroadcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW COSTUME.
        /// </summary>
        public static string Editor_TitleNewCostume {
            get {
                return ResourceManager.GetString("Editor_TitleNewCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SOUND.
        /// </summary>
        public static string Editor_TitleNewSound {
            get {
                return ResourceManager.GetString("Editor_TitleNewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW OBJECT.
        /// </summary>
        public static string Editor_TitleNewSprite {
            get {
                return ResourceManager.GetString("Editor_TitleNewSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT SETTINGS.
        /// </summary>
        public static string Editor_TitleProjectSettings {
            get {
                return ResourceManager.GetString("Editor_TitleProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD SOUND.
        /// </summary>
        public static string Editor_TitleRecorder {
            get {
                return ResourceManager.GetString("Editor_TitleRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name.
        /// </summary>
        public static string Editor_VariableName {
            get {
                return ResourceManager.GetString("Editor_VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationX.
        /// </summary>
        public static string Formula_ACCELERATION_X {
            get {
                return ResourceManager.GetString("Formula_ACCELERATION_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationY.
        /// </summary>
        public static string Formula_ACCELERATION_Y {
            get {
                return ResourceManager.GetString("Formula_ACCELERATION_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerationZ.
        /// </summary>
        public static string Formula_ACCELERATION_Z {
            get {
                return ResourceManager.GetString("Formula_ACCELERATION_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brightness.
        /// </summary>
        public static string Formula_BRIGHTNESS {
            get {
                return ResourceManager.GetString("Formula_BRIGHTNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string Formula_ClosedBrecket {
            get {
                return ResourceManager.GetString("Formula_ClosedBrecket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compassdirec.
        /// </summary>
        public static string Formula_COMPASSDIRECTION {
            get {
                return ResourceManager.GetString("Formula_COMPASSDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Formula_DecimalPointCharacter {
            get {
                return ResourceManager.GetString("Formula_DecimalPointCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        public static string Formula_DIRECTION {
            get {
                return ResourceManager.GetString("Formula_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string Formula_Divide {
            get {
                return ResourceManager.GetString("Formula_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        public static string Formula_FunctionAbs {
            get {
                return ResourceManager.GetString("Formula_FunctionAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arccos.
        /// </summary>
        public static string Formula_FunctionArcCos {
            get {
                return ResourceManager.GetString("Formula_FunctionArcCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arcsin.
        /// </summary>
        public static string Formula_FunctionArcSin {
            get {
                return ResourceManager.GetString("Formula_FunctionArcSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arctan.
        /// </summary>
        public static string Formula_FunctionArcTan {
            get {
                return ResourceManager.GetString("Formula_FunctionArcTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        public static string Formula_FunctionCos {
            get {
                return ResourceManager.GetString("Formula_FunctionCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp.
        /// </summary>
        public static string Formula_FunctionExp {
            get {
                return ResourceManager.GetString("Formula_FunctionExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        public static string Formula_FunctionLn {
            get {
                return ResourceManager.GetString("Formula_FunctionLn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        public static string Formula_FunctionLog {
            get {
                return ResourceManager.GetString("Formula_FunctionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string Formula_FunctionMax {
            get {
                return ResourceManager.GetString("Formula_FunctionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Formula_FunctionMin {
            get {
                return ResourceManager.GetString("Formula_FunctionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod.
        /// </summary>
        public static string Formula_FunctionMod {
            get {
                return ResourceManager.GetString("Formula_FunctionMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pi.
        /// </summary>
        public static string Formula_FunctionPi {
            get {
                return ResourceManager.GetString("Formula_FunctionPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string Formula_FunctionRandom {
            get {
                return ResourceManager.GetString("Formula_FunctionRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        public static string Formula_FunctionRound {
            get {
                return ResourceManager.GetString("Formula_FunctionRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        public static string Formula_FunctionSin {
            get {
                return ResourceManager.GetString("Formula_FunctionSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        public static string Formula_FunctionSqrt {
            get {
                return ResourceManager.GetString("Formula_FunctionSqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        public static string Formula_FunctionTan {
            get {
                return ResourceManager.GetString("Formula_FunctionTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclinationX.
        /// </summary>
        public static string Formula_INCLINATION_X {
            get {
                return ResourceManager.GetString("Formula_INCLINATION_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclinationY.
        /// </summary>
        public static string Formula_INCLINATION_Y {
            get {
                return ResourceManager.GetString("Formula_INCLINATION_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        public static string Formula_LAYER {
            get {
                return ResourceManager.GetString("Formula_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string Formula_LogicAnd {
            get {
                return ResourceManager.GetString("Formula_LogicAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string Formula_LogicEqual {
            get {
                return ResourceManager.GetString("Formula_LogicEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        public static string Formula_LogicFalse {
            get {
                return ResourceManager.GetString("Formula_LogicFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string Formula_LogicGreater {
            get {
                return ResourceManager.GetString("Formula_LogicGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≥.
        /// </summary>
        public static string Formula_LogicGreaterEqual {
            get {
                return ResourceManager.GetString("Formula_LogicGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        public static string Formula_LogicNot {
            get {
                return ResourceManager.GetString("Formula_LogicNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≠.
        /// </summary>
        public static string Formula_LogicNotEqual {
            get {
                return ResourceManager.GetString("Formula_LogicNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Formula_LogicOr {
            get {
                return ResourceManager.GetString("Formula_LogicOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string Formula_LogicSmaller {
            get {
                return ResourceManager.GetString("Formula_LogicSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≤.
        /// </summary>
        public static string Formula_LogicSmallerEqual {
            get {
                return ResourceManager.GetString("Formula_LogicSmallerEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        public static string Formula_LogicTrue {
            get {
                return ResourceManager.GetString("Formula_LogicTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Formula_Minus {
            get {
                return ResourceManager.GetString("Formula_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Formula_Mult {
            get {
                return ResourceManager.GetString("Formula_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectX.
        /// </summary>
        public static string Formula_OBJECT_X {
            get {
                return ResourceManager.GetString("Formula_OBJECT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectY.
        /// </summary>
        public static string Formula_OBJECT_Y {
            get {
                return ResourceManager.GetString("Formula_OBJECT_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string Formula_OpenBrecket {
            get {
                return ResourceManager.GetString("Formula_OpenBrecket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Formula_ParameterSeperator {
            get {
                return ResourceManager.GetString("Formula_ParameterSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string Formula_Plus {
            get {
                return ResourceManager.GetString("Formula_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string Formula_Random {
            get {
                return ResourceManager.GetString("Formula_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string Formula_SIZE {
            get {
                return ResourceManager.GetString("Formula_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparency.
        /// </summary>
        public static string Formula_TRANSPARENCY {
            get {
                return ResourceManager.GetString("Formula_TRANSPARENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Formula_Unknown {
            get {
                return ResourceManager.GetString("Formula_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Code for Windows is an on-device visual programming language and set of creativity tools for Windows Phone 8 devices. It is inspired by the Scratch programming system developed by the Lifelong Kindergarten group at the MIT Media Lab. Pocket Code is an independent free and open source project developed by the Pocket Code team. Pocket Code for Windows is licensed under the MS-RL license..
        /// </summary>
        public static string Main_AboutText {
            get {
                return ResourceManager.GetString("Main_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string Main_ActiveProject {
            get {
                return ResourceManager.GetString("Main_ActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Code for Windows v{0}.
        /// </summary>
        public static string Main_ApplicationNameAndVersion {
            get {
                return ResourceManager.GetString("Main_ApplicationNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Main_ButtonCancel {
            get {
                return ResourceManager.GetString("Main_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Main_ButtonCopy {
            get {
                return ResourceManager.GetString("Main_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string Main_ButtonCreate {
            get {
                return ResourceManager.GetString("Main_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Main_ButtonDelete {
            get {
                return ResourceManager.GetString("Main_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Main_ButtonEdit {
            get {
                return ResourceManager.GetString("Main_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Register.
        /// </summary>
        public static string Main_ButtonLoginRegister {
            get {
                return ResourceManager.GetString("Main_ButtonLoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password forgotten.
        /// </summary>
        public static string Main_ButtonPasswordForgotten {
            get {
                return ResourceManager.GetString("Main_ButtonPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Main_ButtonSave {
            get {
                return ResourceManager.GetString("Main_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string Main_ButtonUpload {
            get {
                return ResourceManager.GetString("Main_ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change name and description.
        /// </summary>
        public static string Main_ChangeProjectNameAndDescription {
            get {
                return ResourceManager.GetString("Main_ChangeProjectNameAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Main_CopyProject {
            get {
                return ResourceManager.GetString("Main_CopyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show memory usage.
        /// </summary>
        public static string Main_DEBUGShowMemory {
            get {
                return ResourceManager.GetString("Main_DEBUGShowMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Main_DeleteProject {
            get {
                return ResourceManager.GetString("Main_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project you chose is being downloaded..
        /// </summary>
        public static string Main_DownloadQueueMessage {
            get {
                return ResourceManager.GetString("Main_DownloadQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string Main_FilterTextBoxHint {
            get {
                return ResourceManager.GetString("Main_FilterTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_HeaderAbout {
            get {
                return ResourceManager.GetString("Main_HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        public static string Main_HeaderCurrentProject {
            get {
                return ResourceManager.GetString("Main_HeaderCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Main_HeaderDesign {
            get {
                return ResourceManager.GetString("Main_HeaderDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Main_HeaderLanguage {
            get {
                return ResourceManager.GetString("Main_HeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string Main_HeaderLocalProjects {
            get {
                return ResourceManager.GetString("Main_HeaderLocalProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Main_HeaderOnlineProjects {
            get {
                return ResourceManager.GetString("Main_HeaderOnlineProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_HeaderSettings {
            get {
                return ResourceManager.GetString("Main_HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Main_ListDesign {
            get {
                return ResourceManager.GetString("Main_ListDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Main_ListLanguage {
            get {
                return ResourceManager.GetString("Main_ListLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to copy &quot;{0}&quot;?.
        /// </summary>
        public static string Main_MainCopyProjectDialogMessage {
            get {
                return ResourceManager.GetString("Main_MainCopyProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy project?.
        /// </summary>
        public static string Main_MainCopyProjectDialogTitle {
            get {
                return ResourceManager.GetString("Main_MainCopyProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Main_MainDeleteProjectDialogMessage {
            get {
                return ResourceManager.GetString("Main_MainDeleteProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project?.
        /// </summary>
        public static string Main_MainDeleteProjectDialogTitle {
            get {
                return ResourceManager.GetString("Main_MainDeleteProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Main_MessageBoxInformation {
            get {
                return ResourceManager.GetString("Main_MessageBoxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All downloads finished..
        /// </summary>
        public static string Main_NoDownloadsPending {
            get {
                return ResourceManager.GetString("Main_NoDownloadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All uploads finished..
        /// </summary>
        public static string Main_NoUploadsPending {
            get {
                return ResourceManager.GetString("Main_NoUploadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description:.
        /// </summary>
        public static string Main_OnlineProjectDescription {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Main_OnlineProjectDownloadButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downloads.
        /// </summary>
        public static string Main_OnlineProjectDownloads {
            get {
                return ResourceManager.GetString("Main_OnlineProjectDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Main_OnlineProjectLicenseButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectLicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string Main_OnlineProjectListBoxLoadMore {
            get {
                return ResourceManager.GetString("Main_OnlineProjectListBoxLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project:.
        /// </summary>
        public static string Main_OnlineProjectProject {
            get {
                return ResourceManager.GetString("Main_OnlineProjectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as unappropriate.
        /// </summary>
        public static string Main_OnlineProjectReportButton {
            get {
                return ResourceManager.GetString("Main_OnlineProjectReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics:.
        /// </summary>
        public static string Main_OnlineProjectStatistics {
            get {
                return ResourceManager.GetString("Main_OnlineProjectStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded:.
        /// </summary>
        public static string Main_OnlineProjectUploaded {
            get {
                return ResourceManager.GetString("Main_OnlineProjectUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by.
        /// </summary>
        public static string Main_OnlineProjectUploadedBy {
            get {
                return ResourceManager.GetString("Main_OnlineProjectUploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (version: {0}).
        /// </summary>
        public static string Main_OnlineProjectVersion {
            get {
                return ResourceManager.GetString("Main_OnlineProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} views.
        /// </summary>
        public static string Main_OnlineProjectViews {
            get {
                return ResourceManager.GetString("Main_OnlineProjectViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string Main_PinProjectToStart {
            get {
                return ResourceManager.GetString("Main_PinProjectToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project does not exist.
        /// </summary>
        public static string Main_ProjectDoesNotExist {
            get {
                return ResourceManager.GetString("Main_ProjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Main_ProjectName {
            get {
                return ResourceManager.GetString("Main_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not valid..
        /// </summary>
        public static string Main_ProjectNotValid {
            get {
                return ResourceManager.GetString("Main_ProjectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The selected project could not be opened..
        /// </summary>
        public static string Main_SelectedProjectNotValidHeader {
            get {
                return ResourceManager.GetString("Main_SelectedProjectNotValidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not valid.
        /// </summary>
        public static string Main_SelectedProjectNotValidMessage {
            get {
                return ResourceManager.GetString("Main_SelectedProjectNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable/disable bricks.
        /// </summary>
        public static string Main_SettingsBricks {
            get {
                return ResourceManager.GetString("Main_SettingsBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mindstorm bricks.
        /// </summary>
        public static string Main_SettingsEnableNXTBricks {
            get {
                return ResourceManager.GetString("Main_SettingsEnableNXTBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Main_SettingsTheme {
            get {
                return ResourceManager.GetString("Main_SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take current project ({0}) as template?.
        /// </summary>
        public static string Main_TakeCurrentProjectAsTemplate {
            get {
                return ResourceManager.GetString("Main_TakeCurrentProjectAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PROJECT.
        /// </summary>
        public static string Main_TitleNewProject {
            get {
                return ResourceManager.GetString("Main_TitleNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Main_TitleSettings {
            get {
                return ResourceManager.GetString("Main_TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD PROJECT.
        /// </summary>
        public static string Main_TitleUploadProject {
            get {
                return ResourceManager.GetString("Main_TitleUploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN OR REGISTER.
        /// </summary>
        public static string Main_TitleUploadProjectLogin {
            get {
                return ResourceManager.GetString("Main_TitleUploadProjectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Main_UploadProjectEmail {
            get {
                return ResourceManager.GetString("Main_UploadProjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your login state is beeing checked!.
        /// </summary>
        public static string Main_UploadProjectLoadingMessage {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error. {0}.
        /// </summary>
        public static string Main_UploadProjectLoginError {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string Main_UploadProjectLoginErrorCaption {
            get {
                return ResourceManager.GetString("Main_UploadProjectLoginErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login- or registration- data is incomplete..
        /// </summary>
        public static string Main_UploadProjectMissingLoginData {
            get {
                return ResourceManager.GetString("Main_UploadProjectMissingLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Main_UploadProjectPassword {
            get {
                return ResourceManager.GetString("Main_UploadProjectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Main_UploadProjectProjectDescription {
            get {
                return ResourceManager.GetString("Main_UploadProjectProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string Main_UploadProjectProjectName {
            get {
                return ResourceManager.GetString("Main_UploadProjectProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful!.
        /// </summary>
        public static string Main_UploadProjectRegistrationSucessful {
            get {
                return ResourceManager.GetString("Main_UploadProjectRegistrationSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error. Error code {0}.
        /// </summary>
        public static string Main_UploadProjectUndefinedError {
            get {
                return ResourceManager.GetString("Main_UploadProjectUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Main_UploadProjectUsername {
            get {
                return ResourceManager.GetString("Main_UploadProjectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string Main_UploadProjectWelcome {
            get {
                return ResourceManager.GetString("Main_UploadProjectWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project is being uploaded. This might take a little while, but we&apos;ll tell you when it&apos;s finished!.
        /// </summary>
        public static string Main_UploadQueueMessage {
            get {
                return ResourceManager.GetString("Main_UploadQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project version is not supported..
        /// </summary>
        public static string Main_VersionIsNotSupported {
            get {
                return ResourceManager.GetString("Main_VersionIsNotSupported", resourceCulture);
            }
        }
    }
}
