//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.Core.Resources.ApplicationResources", typeof(ApplicationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://catroid-test.catrob.at/api/.
        /// </summary>
        public static string API_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("API_BASE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkToken/check.json.
        /// </summary>
        public static string API_CHECK_TOKEN {
            get {
                return ResourceManager.GetString("API_CHECK_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loginOrRegister/loginOrRegister.json.
        /// </summary>
        public static string API_LOGIN_REGISTER {
            get {
                return ResourceManager.GetString("API_LOGIN_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileChecksum.
        /// </summary>
        public static string API_PARAM_CHECKSUM {
            get {
                return ResourceManager.GetString("API_PARAM_CHECKSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flagReason.
        /// </summary>
        public static string API_PARAM_FLAG_REASON {
            get {
                return ResourceManager.GetString("API_PARAM_FLAG_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string API_PARAM_HASH {
            get {
                return ResourceManager.GetString("API_PARAM_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userLanguage.
        /// </summary>
        public static string API_PARAM_LANGUAGE {
            get {
                return ResourceManager.GetString("API_PARAM_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordSavePassword.
        /// </summary>
        public static string API_PARAM_NEW_PWD {
            get {
                return ResourceManager.GetString("API_PARAM_NEW_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordSavePassword2.
        /// </summary>
        public static string API_PARAM_NEW_PWD_REPEAT {
            get {
                return ResourceManager.GetString("API_PARAM_NEW_PWD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectId.
        /// </summary>
        public static string API_PARAM_PROJECTID {
            get {
                return ResourceManager.GetString("API_PARAM_PROJECTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordRecoveryUserdata.
        /// </summary>
        public static string API_PARAM_RECOVER_PWD {
            get {
                return ResourceManager.GetString("API_PARAM_RECOVER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationCountry.
        /// </summary>
        public static string API_PARAM_REG_COUNTRY {
            get {
                return ResourceManager.GetString("API_PARAM_REG_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationEmail.
        /// </summary>
        public static string API_PARAM_REG_EMAIL {
            get {
                return ResourceManager.GetString("API_PARAM_REG_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationPassword.
        /// </summary>
        public static string API_PARAM_REG_PASSWORD {
            get {
                return ResourceManager.GetString("API_PARAM_REG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrationUsername.
        /// </summary>
        public static string API_PARAM_REG_USERNAME {
            get {
                return ResourceManager.GetString("API_PARAM_REG_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string API_PARAM_TOKEN {
            get {
                return ResourceManager.GetString("API_PARAM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string API_PARAM_UPLOAD {
            get {
                return ResourceManager.GetString("API_PARAM_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string API_PARAM_USERNAME {
            get {
                return ResourceManager.GetString("API_PARAM_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects/recent.json?limit={0}&amp;offset={1}.
        /// </summary>
        public static string API_RECENT_PROJECTS {
            get {
                return ResourceManager.GetString("API_RECENT_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string API_REQUEST_LIMIT {
            get {
                return ResourceManager.GetString("API_REQUEST_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects/search.json?query={0}&amp;limit={1}&amp;offset={2}.
        /// </summary>
        public static string API_SEARCH_PROJECTS {
            get {
                return ResourceManager.GetString("API_SEARCH_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload/upload.json.
        /// </summary>
        public static string API_UPLOAD {
            get {
                return ResourceManager.GetString("API_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://developer.catrobat.org/licenses.
        /// </summary>
        public static string CATROBAT_LICENSES_URL {
            get {
                return ResourceManager.GetString("CATROBAT_LICENSES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://catrob.at/tou.
        /// </summary>
        public static string CATROBAT_TOU_URL {
            get {
                return ResourceManager.GetString("CATROBAT_TOU_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.catrobat.org/.
        /// </summary>
        public static string CATROBAT_URL {
            get {
                return ResourceManager.GetString("CATROBAT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordrecovery/changeMyPasswordRequest.json.
        /// </summary>
        public static string CATROWEB_CHANGE_PWD {
            get {
                return ResourceManager.GetString("CATROWEB_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordrecovery/sendMailRequest.json.
        /// </summary>
        public static string CATROWEB_RECOVER_PWD {
            get {
                return ResourceManager.GetString("CATROWEB_RECOVER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flagInappropriate/flag.json.
        /// </summary>
        public static string CATROWEB_REPORT_AS_INAPPROPRIATE {
            get {
                return ResourceManager.GetString("CATROWEB_REPORT_AS_INAPPROPRIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .catrobat.
        /// </summary>
        public static string EXTENSION {
            get {
                return ResourceManager.GetString("EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string MIMETYPE {
            get {
                return ResourceManager.GetString("MIMETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://share.catrob.at/.
        /// </summary>
        public static string POCEKTCODE_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("POCEKTCODE_BASE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pocketcode.org/licenseToPlay.
        /// </summary>
        public static string PROJECT_LICENSE_URL {
            get {
                return ResourceManager.GetString("PROJECT_LICENSE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userEmail.
        /// </summary>
        public static string USER_EMAIL {
            get {
                return ResourceManager.GetString("USER_EMAIL", resourceCulture);
            }
        }
    }
}
