//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDECommon.Resources.Bricks {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrickResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrickResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDECommon.Resources.Bricks.BrickResources", typeof(BrickResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast and wait.
        /// </summary>
        public static string BroadcastWait {
            get {
                return ResourceManager.GetString("BroadcastWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new....
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string CategoryControl {
            get {
                return ResourceManager.GetString("CategoryControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks.
        /// </summary>
        public static string CategoryLooks {
            get {
                return ResourceManager.GetString("CategoryLooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        public static string CategoryMotion {
            get {
                return ResourceManager.GetString("CategoryMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string CategorySound {
            get {
                return ResourceManager.GetString("CategorySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change brightness by.
        /// </summary>
        public static string ChangeBrightnessBy {
            get {
                return ResourceManager.GetString("ChangeBrightnessBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change ghost effect by.
        /// </summary>
        public static string ChangeGhostEffectBy {
            get {
                return ResourceManager.GetString("ChangeGhostEffectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change size by.
        /// </summary>
        public static string ChangeSizeBy {
            get {
                return ResourceManager.GetString("ChangeSizeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change volume by.
        /// </summary>
        public static string ChangeVolumeBy {
            get {
                return ResourceManager.GetString("ChangeVolumeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change X by.
        /// </summary>
        public static string ChangeXBy {
            get {
                return ResourceManager.GetString("ChangeXBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Y by.
        /// </summary>
        public static string ChangeYBy {
            get {
                return ResourceManager.GetString("ChangeYBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear graphic effects.
        /// </summary>
        public static string ClearGraphicEffects {
            get {
                return ResourceManager.GetString("ClearGraphicEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to come to front.
        /// </summary>
        public static string ComeToFront {
            get {
                return ResourceManager.GetString("ComeToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever.
        /// </summary>
        public static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glide.
        /// </summary>
        public static string GlideToGlide {
            get {
                return ResourceManager.GetString("GlideToGlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string GlideToTo {
            get {
                return ResourceManager.GetString("GlideToTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        public static string GoNStepsBackGo {
            get {
                return ResourceManager.GetString("GoNStepsBackGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layers.
        /// </summary>
        public static string GoNStepsBackStepsBack {
            get {
                return ResourceManager.GetString("GoNStepsBackStepsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if on edge, bounce.
        /// </summary>
        public static string IfOnEdgeBounce {
            get {
                return ResourceManager.GetString("IfOnEdgeBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of loop.
        /// </summary>
        public static string LoopEnd {
            get {
                return ResourceManager.GetString("LoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string MoveNStepsMove {
            get {
                return ResourceManager.GetString("MoveNStepsMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps.
        /// </summary>
        public static string MoveNStepsSteps {
            get {
                return ResourceManager.GetString("MoveNStepsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next costume.
        /// </summary>
        public static string NextCostume {
            get {
                return ResourceManager.GetString("NextCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place at.
        /// </summary>
        public static string PlaceAt {
            get {
                return ResourceManager.GetString("PlaceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play sound.
        /// </summary>
        public static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point in direction.
        /// </summary>
        public static string PointInDirection {
            get {
                return ResourceManager.GetString("PointInDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point towards.
        /// </summary>
        public static string PointTo {
            get {
                return ResourceManager.GetString("PointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set brightness to.
        /// </summary>
        public static string SetBrightnessTo {
            get {
                return ResourceManager.GetString("SetBrightnessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set costume.
        /// </summary>
        public static string SetCostume {
            get {
                return ResourceManager.GetString("SetCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set ghost effect to.
        /// </summary>
        public static string SetGhostEffectTo {
            get {
                return ResourceManager.GetString("SetGhostEffectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set size to.
        /// </summary>
        public static string SetSizeTo {
            get {
                return ResourceManager.GetString("SetSizeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set volume to.
        /// </summary>
        public static string SetVolumeTo {
            get {
                return ResourceManager.GetString("SetVolumeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set X to.
        /// </summary>
        public static string SetXTo {
            get {
                return ResourceManager.GetString("SetXTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Y to.
        /// </summary>
        public static string SetYTo {
            get {
                return ResourceManager.GetString("SetYTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speak.
        /// </summary>
        public static string Speak {
            get {
                return ResourceManager.GetString("Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop all sounds.
        /// </summary>
        public static string StopAllSounds {
            get {
                return ResourceManager.GetString("StopAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn left.
        /// </summary>
        public static string TurnLeft {
            get {
                return ResourceManager.GetString("TurnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn right.
        /// </summary>
        public static string TurnRight {
            get {
                return ResourceManager.GetString("TurnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when I receive.
        /// </summary>
        public static string WhenIReceive {
            get {
                return ResourceManager.GetString("WhenIReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when project starts.
        /// </summary>
        public static string WhenProjectStarts {
            get {
                return ResourceManager.GetString("WhenProjectStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when tapped.
        /// </summary>
        public static string WhenTapped {
            get {
                return ResourceManager.GetString("WhenTapped", resourceCulture);
            }
        }
    }
}
