//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catrobat.IDECommon.Resources.Main {
    using System;
  using System.Reflection;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catrobat.IDECommon.Resources.Main.MainResources", typeof(MainResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catrobat for Windows is an on-device visual progamming language for Windows Phone 8 devices that is inspired by the scratch programming language developed by the MIT.
        ///It is developed at the department of Software Technology at the University of Technology Graz, Austria.
        ///The program is licensed under the MS-RL Lizenz..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string ActiveProject {
            get {
                return ResourceManager.GetString("ActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catrobat for Windows v{0}.
        /// </summary>
        public static string ApplicationNameAndVersion {
            get {
                return ResourceManager.GetString("ApplicationNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Register.
        /// </summary>
        public static string ButtonLoginRegister {
            get {
                return ResourceManager.GetString("ButtonLoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password forgotten.
        /// </summary>
        public static string ButtonPasswordForgotten {
            get {
                return ResourceManager.GetString("ButtonPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show memory usage.
        /// </summary>
        public static string DEBUGShowMemory {
            get {
                return ResourceManager.GetString("DEBUGShowMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project you chose is being downloaded. This might take a little while, but we&apos;ll tell you when it&apos;s finished!.
        /// </summary>
        public static string DownloadQueueMessage {
            get {
                return ResourceManager.GetString("DownloadQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string FilterTextBoxHint {
            get {
                return ResourceManager.GetString("FilterTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HeaderAbout {
            get {
                return ResourceManager.GetString("HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        public static string HeaderCurrentProject {
            get {
                return ResourceManager.GetString("HeaderCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string HeaderDesign {
            get {
                return ResourceManager.GetString("HeaderDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string HeaderLanguage {
            get {
                return ResourceManager.GetString("HeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string HeaderLocalProjects {
            get {
                return ResourceManager.GetString("HeaderLocalProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string HeaderOnlineProjects {
            get {
                return ResourceManager.GetString("HeaderOnlineProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string ListDesign {
            get {
                return ResourceManager.GetString("ListDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ListLanguage {
            get {
                return ResourceManager.GetString("ListLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to copy &quot;{0}&quot;?.
        /// </summary>
        public static string MainCopyProjectDialogMessage {
            get {
                return ResourceManager.GetString("MainCopyProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy project?.
        /// </summary>
        public static string MainCopyProjectDialogTitle {
            get {
                return ResourceManager.GetString("MainCopyProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string MainDeleteProjectDialogMessage {
            get {
                return ResourceManager.GetString("MainDeleteProjectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project?.
        /// </summary>
        public static string MainDeleteProjectDialogTitle {
            get {
                return ResourceManager.GetString("MainDeleteProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBoxInformation {
            get {
                return ResourceManager.GetString("MessageBoxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All downloads have finished..
        /// </summary>
        public static string NoDownloadsPending {
            get {
                return ResourceManager.GetString("NoDownloadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All uploads have finished..
        /// </summary>
        public static string NoUploadsPending {
            get {
                return ResourceManager.GetString("NoUploadsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description:.
        /// </summary>
        public static string OnlineProjectDescription {
            get {
                return ResourceManager.GetString("OnlineProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string OnlineProjectDownloadButton {
            get {
                return ResourceManager.GetString("OnlineProjectDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downloads.
        /// </summary>
        public static string OnlineProjectDownloads {
            get {
                return ResourceManager.GetString("OnlineProjectDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string OnlineProjectLicenseButton {
            get {
                return ResourceManager.GetString("OnlineProjectLicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string OnlineProjectListBoxLoadMore {
            get {
                return ResourceManager.GetString("OnlineProjectListBoxLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project:.
        /// </summary>
        public static string OnlineProjectProject {
            get {
                return ResourceManager.GetString("OnlineProjectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as unappropriate.
        /// </summary>
        public static string OnlineProjectReportButton {
            get {
                return ResourceManager.GetString("OnlineProjectReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics:.
        /// </summary>
        public static string OnlineProjectStatistics {
            get {
                return ResourceManager.GetString("OnlineProjectStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded:.
        /// </summary>
        public static string OnlineProjectUploaded {
            get {
                return ResourceManager.GetString("OnlineProjectUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by.
        /// </summary>
        public static string OnlineProjectUploadedBy {
            get {
                return ResourceManager.GetString("OnlineProjectUploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (version: {0}).
        /// </summary>
        public static string OnlineProjectVersion {
            get {
                return ResourceManager.GetString("OnlineProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} views.
        /// </summary>
        public static string OnlineProjectViews {
            get {
                return ResourceManager.GetString("OnlineProjectViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable/disable bricks.
        /// </summary>
        public static string SettingsBricks {
            get {
                return ResourceManager.GetString("SettingsBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mindstorm bricks.
        /// </summary>
        public static string SettingsEnableNXTBricks {
            get {
                return ResourceManager.GetString("SettingsEnableNXTBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PROJECT.
        /// </summary>
        public static string TitleNewProject {
            get {
                return ResourceManager.GetString("TitleNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD PROJECT.
        /// </summary>
        public static string TitleUploadProject {
            get {
                return ResourceManager.GetString("TitleUploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN OR REGISTER.
        /// </summary>
        public static string TitleUploadProjectLogin {
            get {
                return ResourceManager.GetString("TitleUploadProjectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string UploadProjectEmail {
            get {
                return ResourceManager.GetString("UploadProjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error. {0}.
        /// </summary>
        public static string UploadProjectLoginError {
            get {
                return ResourceManager.GetString("UploadProjectLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string UploadProjectLoginErrorCaption {
            get {
                return ResourceManager.GetString("UploadProjectLoginErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login- or registration- data is incomplete..
        /// </summary>
        public static string UploadProjectMissingLoginData {
            get {
                return ResourceManager.GetString("UploadProjectMissingLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string UploadProjectPassword {
            get {
                return ResourceManager.GetString("UploadProjectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string UploadProjectProjectDescription {
            get {
                return ResourceManager.GetString("UploadProjectProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string UploadProjectProjectName {
            get {
                return ResourceManager.GetString("UploadProjectProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful!.
        /// </summary>
        public static string UploadProjectRegistrationSucessful {
            get {
                return ResourceManager.GetString("UploadProjectRegistrationSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error. Error code {0}.
        /// </summary>
        public static string UploadProjectUndefinedError {
            get {
                return ResourceManager.GetString("UploadProjectUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UploadProjectUsername {
            get {
                return ResourceManager.GetString("UploadProjectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string UploadProjectWelcome {
            get {
                return ResourceManager.GetString("UploadProjectWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project is being uploaded. This might take a little while, but we&apos;ll tell you when it&apos;s finished!.
        /// </summary>
        public static string UploadQueueMessage {
            get {
                return ResourceManager.GetString("UploadQueueMessage", resourceCulture);
            }
        }
    }
}
